Fix FT.CREATE example and add example for document scoring
RedisLabs/redislabs-docs pull request #1077
Opened 2020-10-21 12:18 UTC by elena-kolevska

Changing the score field name in the FT.CREATE example to something else than the reserved `WEIGHT`.
Currently, the following error is returned:

```
(error) Bad arguments for weight: Could not convert argument to expected type
```

Added an example for document scoring.

2020-10-22 15:00 UTC, K-Jo commented
@elena-kolevska isn't it confusing that the field for the score is also indexed?

2020-10-23 08:27 UTC, elena-kolevska commented
@K-Jo That's how it was before, in the example, so I thought it has to be. If that's not the case, then yes, I'd say it's better to remove it.

2020-10-25 17:06 UTC, K-Jo commented
Can you please remove it from the schema?  Or add another field to the schema that isn't the doc change @elena-kolevska @bmansheim

2020-10-26 12:49 UTC, elena-kolevska commented
@K-Jo Ok, done. There were a few other small things that needed to be fixed, I corrected them too, as well as adding a sentence or two more on document scoring.

2020-10-26 13:34 UTC, bmansheim requested changes

2020-10-26 13:34 UTC, bmansheim commented on content/embeds/tryout-redisearch-2.md
> +    By default, all hashes get a score of 1.0, but if we need to be able to assign document-specific score to documents, we can do that too. We only need to specify in the schema the name of the hash
```suggestion
    By default, all hashes get a score of 1.0, but if we need to assign a document-specific score to documents, we can do that too.
    We only need to specify in the schema the name of the hash element in which we will define the document score that overrides the default of 1.0. This is done by using the `SCORE_FIELD` directive.
```

2020-10-26 13:34 UTC, bmansheim commented on content/embeds/tryout-redisearch-2.md
> +To add a document specific score, causing the document to appear higher or lower in results, set a value for the `doc_weight` field, which we specified as the `SCORE_FIELD` in the schema definition:
```suggestion
To add a document specific score that causes the document to appear higher or lower in results, set a value for the `doc_weight` field.
We specified the `SCORE_FIELD` in the schema definition to hold the document weight value.
```

2020-10-26 14:40 UTC, elena-kolevska commented on content/embeds/tryout-redisearch-2.md
> +    By default, all hashes get a score of 1.0, but if we need to be able to assign document-specific score to documents, we can do that too. We only need to specify in the schema the name of the hash
Sorry @bmansheim , I had committed some other changes without seeing your request. Applied now.

2020-11-02 12:14 UTC, bmansheim commented
@K-Jo We're ready to go on this, right?

2020-11-03 09:47 UTC, K-Jo approved these changes

2020-11-04 09:46 UTC, bmansheim approved these changes

2020-11-04 09:46 UTC, merged