Update cluster-options.md
RedisLabs/redislabs-docs pull request #1116
Opened 2020-11-26 00:03 UTC by yanivhershkovich

The link specified next to the field names leads to 404 not found page.
Need to update with the correct link.

I just added "<<Need URL Update>>" next to each URL to point to it.
Remove that string once the URL is updated.

2020-11-26 00:06 UTC, yanivhershkovich commented
Looks like my comment was truncated.
I added `<<Need URL Update>>` next to each URL that needs to be updated.
That string should be removed once the URL is updated

2020-11-26 12:44 UTC, bmansheim commented
@alexmilowski Can you point these links to the operator.md file? It looks like it was moved.

2020-12-03 17:44 UTC, alexmilowski requested changes

2020-12-03 17:44 UTC, alexmilowski commented on content/platforms/kubernetes/cluster-options.md
> +- [`nodes`](https://github.com/RedisLabs/redis-enterprise-k8s-docs/blob/master/docs/operator.md#redisenterpriseclusterspec) <<Need URL Update>>: `nnn`
https://github.com/RedisLabs/redis-enterprise-k8s-docs/blob/master/redis_enterprise_cluster_api.md#redisenterpriseclusterspec

2020-12-03 17:44 UTC, alexmilowski commented on content/platforms/kubernetes/cluster-options.md
> +- [`persistentSpec`](https://github.com/RedisLabs/redis-enterprise-k8s-docs/blob/master/docs/operator.md#persistentconfigurationspec) <<Need URL Update>>:
https://github.com/RedisLabs/redis-enterprise-k8s-docs/blob/master/redis_enterprise_cluster_api.md#redisenterpriseclusterspec

2020-12-03 17:44 UTC, alexmilowski commented on content/platforms/kubernetes/cluster-options.md
> +- [`redisEnterpriseNodeResources`](https://github.com/RedisLabs/redis-enterprise-k8s-docs/blob/master/docs/operator.md#redisenterpriseclusterspec) <<Need URL Update>>:
https://github.com/RedisLabs/redis-enterprise-k8s-docs/blob/master/redis_enterprise_cluster_api.md#redisenterpriseclusterspec

2020-12-03 17:44 UTC, alexmilowski commented on content/platforms/kubernetes/cluster-options.md
> +    - [`limits`](https://github.com/RedisLabs/redis-enterprise-k8s-docs/blob/master/docs/operator.md#redisenterpriseclusterspec) <<Need URL Update>>:
https://github.com/RedisLabs/redis-enterprise-k8s-docs/blob/master/redis_enterprise_cluster_api.md#redisenterpriseclusterspec

2020-12-03 17:44 UTC, alexmilowski commented on content/platforms/kubernetes/cluster-options.md
> +    - [`requests`](https://github.com/RedisLabs/redis-enterprise-k8s-docs/blob/master/docs/operator.md#redisenterpriseclusterspec) <<Need URL Update>>:
https://github.com/RedisLabs/redis-enterprise-k8s-docs/blob/master/redis_enterprise_cluster_api.md#redisenterpriseclusterspec

2020-12-03 17:44 UTC, alexmilowski commented on content/platforms/kubernetes/cluster-options.md
> +- [`serviceBrokerSpec`](https://github.com/RedisLabs/redis-enterprise-k8s-docs/blob/master/docs/operator.md#servicebrokerspec) <<Need URL Update>>:
This item needs to be deleted.

2020-12-03 17:44 UTC, alexmilowski commented on content/platforms/kubernetes/cluster-options.md
> +- [`redisEnterpriseImageSpec`](https://github.com/RedisLabs/redis-enterprise-k8s-docs/blob/master/docs/operator.md#imagespec) <<Need URL Update>>:
https://github.com/RedisLabs/redis-enterprise-k8s-docs/blob/master/redis_enterprise_cluster_api.md#imagespec

2020-12-06 13:22 UTC, merged