no-AA-eviction-RoF.md
RedisLabs/redislabs-docs pull request #1281
Opened 2021-03-21 16:19 UTC by AlonMagrafta

I forgot that

2021-03-21 16:27 UTC, AlonMagrafta commented
@kaitlynmichael I forgot that, can you also verify my syntax of the notes, I have a feeling I might messed up with the spaces ;)

2021-03-22 15:38 UTC, kaitlynmichael requested changes

2021-03-22 15:38 UTC, kaitlynmichael commented on content/rs/administering/creating-databases/create-active-active.md
> +
```suggestion
```

2021-03-22 15:38 UTC, kaitlynmichael commented on content/rs/administering/creating-databases/create-active-active.md
> +
```suggestion
```

2021-03-22 15:38 UTC, kaitlynmichael commented on content/rs/administering/creating-databases/create-active-active.md
> +- Data eviction policy is not supported for Active-Active databases with Redis on Flash (RoF).
```suggestion
- Data eviction policies are not supported for Active-Active databases with Redis on Flash (RoF).
```

2021-03-22 15:38 UTC, kaitlynmichael commented on content/rs/administering/database-operations/eviction-policy.md
> +
```suggestion
```

2021-03-22 15:38 UTC, kaitlynmichael commented on content/rs/administering/database-operations/eviction-policy.md
> +
```suggestion
```

2021-03-22 15:38 UTC, kaitlynmichael commented on content/rs/administering/database-operations/eviction-policy.md
> +- Data eviction policy is not supported for Active-Active databases with Redis on Flash (RoF).
```suggestion
- Data eviction policies are not supported for Active-Active databases with Redis on Flash (RoF).
```

2021-03-22 16:00 UTC, kaitlynmichael approved these changes

2021-03-22 16:53 UTC, merged