Replication backlog [doc-680]
RedisLabs/redislabs-docs pull request #1389
Opened 2021-06-03 12:01 UTC by AlonMagrafta

@lanceleonard @kaitlynmichael please review my english, wording etc :) I assume we will iterate (a bit) on it

2021-06-03 12:48 UTC, lanceleonard requested changes
Should we also add info describing where to find the replication log?

2021-06-03 12:48 UTC, lanceleonard commented on content/rs/administering/database-operations/updating-configurations.md
> +Active-Active and Active-Passive databases are maintaining a Replication Backlog to keep synchronization among the clusters.
```suggestion
Active-Active and Active-Passive databases maintain a Replication Backlog to synchronize clusters.
```

2021-06-03 12:48 UTC, lanceleonard commented on content/rs/administering/database-operations/updating-configurations.md
> +By default, the Replication Backlog size will be set automatically allocated to 1% of the database size and be limited in the range of 1MB (min) - 250MB (max) per shard.
```suggestion
By default, the replication backlog is set to one percent (1%) of the database size and ranges between 1MB to 250MB per shard.
```

2021-06-03 12:48 UTC, lanceleonard commented on content/rs/administering/database-operations/updating-configurations.md
> +It is also possible to toggle between the automatic allocation to a manual size allocation from the command-line:
```suggestion
Use the [crdb-cli]({{< relref "rs/references/crdb-cli-reference.md" >}}) utility to control the size of the replication backlog.  You can set it to `auto` or set a specific size.  

The syntax varies between Active-Active and Active-Passive databases. 
```

2021-06-03 12:48 UTC, lanceleonard commented on content/rs/administering/database-operations/updating-configurations.md
> +For an Active-Active database use [crdb-cli]({{< relref "rs/references/crdb-cli-reference.md" >}}) to run:
```suggestion
For an Active-Active database:
```

2021-06-03 12:48 UTC, lanceleonard commented on content/rs/administering/database-operations/updating-configurations.md
> +For an Active-Passive database use [rladmin]({{< relref "rs/references/rladmin.md" >}}) from the source database and run:
```suggestion
For an Active-Passive database:
```

2021-06-03 12:48 UTC, lanceleonard commented on content/rs/administering/database-operations/updating-configurations.md
> +**For Redis Software before version 6.0.20:**
```suggestion
**For Redis Software versions earlier than 6.0.20:**
```

2021-06-03 12:48 UTC, lanceleonard commented on content/rs/administering/database-operations/updating-configurations.md
> +Replication backlog is set by default to 1MB and is can not be set dynamically ('auto' mode).
```suggestion
The Replication backlog defaults to 1MB and cannot be set dynamically ('auto' mode).
```

2021-06-03 12:48 UTC, lanceleonard commented on content/rs/administering/database-operations/updating-configurations.md
> +Tuning is possible only using [rladmin]({{< relref "rs/references/rladmin.md" >}}) applying to a local intanse of the database on each cluster.
```suggestion
To control the size of the replication log, use [rladmin]({{< relref "rs/references/rladmin.md" >}}) to tune the local database instance in each cluster.
```

2021-06-03 18:51 UTC, kaitlynmichael requested changes

2021-06-03 18:51 UTC, kaitlynmichael commented on content/rs/administering/database-operations/updating-configurations.md
> +Active-Active and Active-Passive databases maintain a Replication Backlog to synchronize clusters.
```suggestion
Active-Active and Active-Passive databases maintain a replication backlog to synchronize clusters.
```
I don't believe these need to be capitalized

2021-06-03 18:51 UTC, kaitlynmichael commented on content/rs/administering/database-operations/updating-configurations.md
> +## Replication Backlog
```suggestion
## Replication backlog
```
We use sentence case

2021-06-03 18:51 UTC, kaitlynmichael commented on content/rs/administering/database-operations/updating-configurations.md
> +The Replication backlog defaults to 1MB and cannot be set dynamically ('auto' mode).
```suggestion
The replication backlog defaults to 1MB and cannot be set dynamically with 'auto' mode.
```

2021-06-07 17:44 UTC, kaitlynmichael approved these changes

2021-06-07 17:46 UTC, lanceleonard approved these changes
LGTM

2021-06-07 17:47 UTC, merged

2021-06-08 08:11 UTC, AlonMagrafta commented
@kaitlynmichael @lanceleonard 
I figured out I need to modify things here. Please don't merge to latest yet. Thanks.