HTTP to HTTPS redirection
RedisLabs/redislabs-docs pull request #1407
Opened 2021-06-17 15:55 UTC by AlonMagrafta

@lanceleonard @kaitlynmichael if I can kindly ask you to review me.
@guyco-redis FYI and thanks!
This is how Guy described it: (for more context)

> Starting version 6.0.12, automatic HTTP to HTTPS redirection is disabled.
> This means that if you want to poll metrics from metrics exporter, or access the CM, you’ll need to explicitly use https in your request, instead of relying on the RS old mechanism that automatically redirected all http requests to https for these services.

2021-06-17 15:58 UTC, AlonMagrafta commented
https://redislabs.atlassian.net/browse/RED-58146

2021-06-17 16:02 UTC, kaitlynmichael requested changes

2021-06-17 16:02 UTC, kaitlynmichael commented on content/rs/administering/designing-production/networking/port-configurations.md
> +Starting version 6.0.12, the automatic HTTP to HTTPS redirection is disabled.
```suggestion
Starting with version 6.0.12, the automatic HTTP to HTTPS redirection is disabled.
```

2021-06-17 16:02 UTC, kaitlynmichael commented on content/rs/administering/designing-production/networking/port-configurations.md
> +To poll metrics from the metrics_exporter, or to access the web UI (the CM), use HTTPS in your request, as HTTP requests won't be automatically redirected to HTTPS for those services.
```suggestion
To poll metrics from the `metrics_exporter` or to access the admin console, use HTTPS in your request. HTTP requests won't be automatically redirected to HTTPS for those services. 
```

2021-06-17 16:12 UTC, lanceleonard approved these changes
Approved with Kaitlyn's modifications

2021-07-06 17:45 UTC, kaitlynmichael approved these changes

2021-07-06 17:45 UTC, merged