Updating admin password on Clusters with CRDB
RedisLabs/redislabs-docs pull request #1474
Opened 2021-08-02 11:23 UTC by AlonMagrafta

not bounded to version, can be merged to latest once approved

2021-08-02 14:52 UTC, kaitlynmichael requested changes

2021-08-02 14:52 UTC, kaitlynmichael commented on content/rs/security/admin-console-security/user-security.md
> +Active-Active databases are relying on the Administrator credentials for management operations of the Active-Active database.
```suggestion
Active-Active databases are relying on the administrator credentials for management operations of the Active-Active database.
```

2021-08-02 14:52 UTC, kaitlynmichael commented on content/rs/security/admin-console-security/user-security.md
> +Do not perform any management operation on the databases between these two steps.
```suggestion
{{< warnging> }}Do not perform any management operation on the databases between these two steps. {{< /warning >}}
```

2021-08-02 14:52 UTC, kaitlynmichael commented on content/rs/security/admin-console-security/user-security.md
> +1. Go to each participating cluster and for each Active-Active database update the Admin user/s credentials that have you changed on step 1.
```suggestion
1. Go to each participating cluster and for each Active-Active database update the admin user credentials that have you changed with the last step. 
```

2021-08-02 16:26 UTC, lanceleonard approved these changes
LGTM (some suggested wording changes).

2021-08-02 16:26 UTC, lanceleonard commented on content/rs/security/admin-console-security/user-security.md
> +1. From the user management page, update the administrator user password on the cluster/s you wish to update.
```suggestion
1. From the user management page, update the administrator user password on the clusters you wish to update.
```

2021-08-02 16:26 UTC, lanceleonard commented on content/rs/security/admin-console-security/user-security.md
> +Active-Active databases are relying on the administrator credentials for management operations of the Active-Active database.
```suggestion
Active-Active databases use administrator credentials to manage operations for Active-Active database.
```

2021-08-02 16:26 UTC, lanceleonard commented on content/rs/security/admin-console-security/user-security.md
> +When updating an administrator user password on a cluster with Active-Active databases please follow these steps:
```suggestion
To update the administrator user password on a cluster with Active-Active databases:
```

2021-08-02 16:26 UTC, lanceleonard commented on content/rs/security/admin-console-security/user-security.md
> +1. Go to each participating cluster and for each Active-Active database update the admin user credentials that have you changed with the last step.
```suggestion
1. For each participating cluster _and_ each Active-Active database, update the admin user credentials to match the changes in Step 1. 
```

2021-08-02 16:26 UTC, lanceleonard commented on content/rs/security/admin-console-security/user-security.md
> +{{< warnging> }}Do not perform any management operation on the databases between these two steps. {{< /warning >}}
```suggestion
{{< warning> }}Do not perform any management operation on the databases until these steps are complete. {{< /warning >}}
```

2021-08-02 16:27 UTC, lanceleonard commented on content/rs/security/admin-console-security/user-security.md
> +## Updating Administrator password on Clusters with Active-Active databases
```suggestion
## Update Active-Active cluster admin credentials
```

2021-08-03 06:57 UTC, AlonMagrafta commented
LGTM

2021-08-03 15:18 UTC, lanceleonard approved these changes

2021-08-03 15:20 UTC, merged