DOC-818 K8s Galactica release changes
RedisLabs/redislabs-docs pull request #1527
Opened 2021-09-09 20:47 UTC by kaitlynmichael

DOC-818 
updated supported distros

2021-09-10 14:25 UTC, rrelledge approved these changes

2021-09-10 20:58 UTC, kaitlynmichael commented on content/platforms/release-notes/k8s-6-2-4-tbd-2021-09.md
> +The Redis Enterprise [K8s 6.2.4-55](https://github.com/RedisLabs/redis-enterprise-k8s-docs/releases/tag/v6.2.4-55) release provides support for the [Redis Enterprise Software release 6.2.4]({{<relref
```suggestion
The Redis Enterprise [K8s 6.2.4-55](https://github.com/RedisLabs/redis-enterprise-k8s-docs/releases/tag/v6.2.4-55) release provides support for the [Redis Enterprise Software release 6.2.4]({{<relref "/rs/release-notes/rs-6-2-4-august-2021/">}}) and includes several enhancements and bug fixes.
```

2021-09-10 20:59 UTC, kaitlynmichael commented on content/platforms/release-notes/k8s-6-2-4-tbd-2021-09.md
> +* **Redis Enterprise**: `redislabs/redis:6.2.4-55` or  redislabs/redis:6.2.4-55.rhel7-openshift`
```suggestion
* **Redis Enterprise**: `redislabs/redis:6.2.4-55` or  `redislabs/redis:6.2.4-55.rhel7-openshift`
```

2021-09-10 21:07 UTC, kaitlynmichael commented on content/platforms/release-notes/k8s-6-2-4-tbd-2021-09.md
> +The Redis Enterprise [K8s 6.2.4-55](https://github.com/RedisLabs/redis-enterprise-k8s-docs/releases/tag/v6.2.4-55) release provides support for the [Redis Enterprise Software release 6.2.4]({{<relref
```suggestion
The Redis Enterprise [K8s 6.2.4-55](https://github.com/RedisLabs/redis-enterprise-k8s-docs/releases/tag/v6.2.4-55) release provides support for the [Redis Enterprise Software release 6.2.4]({{<relref "/rs/release-notes/rs-6-2-4-august-2021.md">}}) and includes several enhancements and bug fixes.
```

2021-09-12 07:41 UTC, yuvallevy2 approved these changes

2021-09-13 14:17 UTC, rrelledge approved these changes
I left a few small suggestions.

2021-09-13 14:17 UTC, rrelledge commented on content/platforms/release-notes/k8s-6-2-4-tbd-2021-09.md
> +* Fixed issue with RS pods not recovering from container fails (RED-)
Missing RED- ticket number?

2021-09-13 14:17 UTC, rrelledge commented on content/platforms/release-notes/k8s-6-2-4-tbd-2021-09.md
> +In OLM-deployed operators, the deployment of the cluster will fail if the name is not "rec". When the operator is deployed via the OLM, the security context constraints (scc) is bound to a specific s
```suggestion
In OLM-deployed operators, the deployment of the cluster will fail if the name is not "rec". When the operator is deployed via the OLM, the security context constraints (scc) are bound to a specific service account name (i.e., "rec"). The workaround is to name the cluster "rec".
```

2021-09-13 14:17 UTC, rrelledge commented on content/platforms/release-notes/k8s-6-2-4-tbd-2021-09.md
> +There is not workaround at this time except to ignore the errors.
```suggestion
There is no workaround at this time except to ignore the errors.
```

2021-09-13 14:17 UTC, rrelledge commented on content/platforms/release-notes/k8s-6-2-4-tbd-2021-09.md
> +The Redis Enterprise [K8s 6.2.4-55](https://github.com/RedisLabs/redis-enterprise-k8s-docs/releases/tag/v6.2.4-55) release provides support for the [Redis Enterprise Software release 6.2.4]({{<relref
The K8s 6.2.4-55 link currently gives me a 404, but maybe this is just a GitHub permissions issue on my part though?

2021-09-14 17:32 UTC, amiramm requested changes
@kaitlynmichael thanks so much for putting this together - had some minor adjustments to share.

2021-09-14 17:32 UTC, amiramm commented on content/platforms/release-notes/k8s-6-2-4-tbd-2021-09.md
> +The Redis Enterprise [K8s 6.2.4-55](https://github.com/RedisLabs/redis-enterprise-k8s-docs/releases/tag/v6.2.4-55) release provides support for the [Redis Enterprise Software release 6.2.4]({{<relref
```suggestion
The Redis Enterprise [K8s 6.2.4-55](https://github.com/RedisLabs/redis-enterprise-k8s-docs/releases/tag/v6.2.4-1) release provides support for the [Redis Enterprise Software release 6.2.4]({{<relref "/rs/release-notes/rs-6-2-4-august-2021.md">}}) and includes several enhancements and bug fixes.
```
@kaitlynmichael @rrelledge I need to tag the release. likely late on 9/14.

2021-09-14 17:32 UTC, amiramm commented on content/platforms/release-notes/k8s-6-2-4-tbd-2021-09.md
> +* **Operator**: `redislabs/operator:6.2.4-<tbd>`
```suggestion
* **Operator**: `redislabs/operator:6.2.4-1`
```

2021-09-14 17:32 UTC, amiramm commented on content/platforms/release-notes/k8s-6-2-4-tbd-2021-09.md
> +* **Services Rigger**: `redislabs/k8s-controller:6.0.20-<tbd>` or `redislabs/services-manager:6.2.4-<tbd>` (on the Red Hat registry)
```suggestion
* **Services Rigger**: `redislabs/k8s-controller:6.0.20-1` or `redislabs/services-manager:6.2.4-1` (on the Red Hat registry)
```

2021-09-14 17:32 UTC, amiramm commented on content/platforms/release-notes/k8s-6-2-4-tbd-2021-09.md
> +* Fixed issue with RS pods not recovering from container fails (RED-)
```suggestion
* Fixed issue with RS pods not recovering from container failures (RED-53042)
```

2021-09-14 17:32 UTC, amiramm commented on content/platforms/release-notes/k8s-6-2-4-tbd-2021-09.md
> +* Fixed rare problem of RS pod restarting too early while statefulSet was rolling out, causing quorum loss (RED-53042)
```suggestion
* Fixed rare problem of Redis Enterprise pod restarting too early while statefulSet was rolling out, causing quorum loss (RED-53042)
```

2021-09-14 17:32 UTC, amiramm commented on content/platforms/release-notes/k8s-6-2-4-tbd-2021-09.md
> +* VMWare TKGIE 1.7 (K8s 1.16), VMWare TKGIE 1.8 (K8s 1.17) are deprecated (no longer supported by VMWare)
@kaitlynmichael additional deprecation
```suggestion
* VMWare TKGIE 1.7 (K8s 1.16), VMWare TKGIE 1.8 (K8s 1.17) are deprecated (no longer supported by VMWare)
* Openshift 3.11 (K8s 1.11) is now deprecated. Redis will continue to support existing deployments for the lifetime of Openshift 3.11, but new deployments are strongly discouraged.
```

2021-09-14 17:55 UTC, amiramm commented on content/platforms/release-notes/k8s-6-2-4-tbd-2021-09.md
> +* Support for addition attribute in REDB secret containing comma seperated list of service names (RED-48469)
```suggestion
* Support for addition attribute in REDB secret containing comma separated list of service names (RED-48469)
```

2021-09-14 20:03 UTC, laurentdroin commented
Can we add a new limitation that says that the length of the REC name + the length of the namespace name must be <= 45 characters?
This comes from https://redislabs.atlassian.net/browse/RED-62222

2021-09-14 20:57 UTC, merged