Update updating-certificates.md
RedisLabs/redislabs-docs pull request #1677
Opened 2021-11-25 16:55 UTC by AlonMagrafta

ready for review, please ping Alon before merging - we are validating this procedure in QA

2021-12-06 17:34 UTC, lanceleonard requested changes
Reworked to match our voice & tone style; please make sure I didn't lose any technical details.

2021-12-06 17:34 UTC, lanceleonard commented on content/rs/administering/cluster-operations/updating-certificates.md
> +Read bellow about updating your proxy and syncer certificates for Active-Active and Actice-Passive (Replica Of) Redis databases.
```suggestion
The following sections describe how to update proxy and syncer certificates for Active-Active and Active-Passive (Replica Of) databases.
```

2021-12-06 17:34 UTC, lanceleonard commented on content/rs/administering/cluster-operations/updating-certificates.md
> +To update your proxy certificate on cluster/s running Active-Active databases follow these steps:
```suggestion
To update proxy certificate on clusters running Active-Active databases:
```

2021-12-06 17:34 UTC, lanceleonard commented on content/rs/administering/cluster-operations/updating-certificates.md
> +- **Step 1:** Update your proxy certificate on one or more of the participating clusters using the `rladmin` command, or REST API. You can update a single cluster, multiple clusters, or all participa
```suggestion
- **Step 1:** Use `rladmin` or the REST API to update proxy certificates on a single cluster, multiple clusters, or all participating clusters.
```

2021-12-06 17:34 UTC, lanceleonard commented on content/rs/administering/cluster-operations/updating-certificates.md
> +- **Step 2:** Update the Active-Active database configuration from the command-line with the [`crdb-cli`]({{< relref "rs/references/crdb-cli-reference.md" >}}) utility. Run this command once for each
```suggestion
- **Step 2:** Use the [`crdb-cli`]({{< relref "rs/references/crdb-cli-reference.md" >}}) utility to update Active-Active database configuration from the command-line. Run the following command once for each Active-Active database residing on the modified clusters.
```

2021-12-06 17:34 UTC, lanceleonard commented on content/rs/administering/cluster-operations/updating-certificates.md
> +- It is required that you run step 2 shortly as possible after step 1, since between the two steps new syncer connections that use the ‘old’ certificate will get rejected by the cluster that has been
```suggestion
- Perform Step 2 as quickly as possible after performing Step 1.  Connections using the previous certificate are rejected by the new certificate.  Until both steps are performed, the database will be unable to sync.
```

2021-12-06 17:34 UTC, lanceleonard commented on content/rs/administering/cluster-operations/updating-certificates.md
> +To update your proxy certificate on cluster/s running Active-Passive (Replica Of) databases follow these steps:
```suggestion
To update proxy certificate on clusters running Active-Passive (Replica Of) databases:
```

2021-12-06 17:34 UTC, lanceleonard commented on content/rs/administering/cluster-operations/updating-certificates.md
> +- **Step 1:** Update your proxy certificate on the source database cluster using the `rladmin` command, or REST API.
```suggestion
- **Step 1:**  Use `rladmin` or the REST API to update proxy certificate on the source database cluster.
```

2021-12-06 17:34 UTC, lanceleonard commented on content/rs/administering/cluster-operations/updating-certificates.md
> +- **Step 2:** From the admin console, update the destination database configuration with the new certificate as described [`here`](https://docs.redis.com/latest/rs/administering/creating-databases/cr
```suggestion
- **Step 2:** From the admin console, update the destination database (_replica_) configuration with the [new certificate]({{<relref "/administering/creating-databases/create-active-passive#configuring-tls-for-replica-of-traffic-on-the-destination-database">}}).
```

2021-12-06 17:34 UTC, lanceleonard commented on content/rs/administering/cluster-operations/updating-certificates.md
> +- It is required that you perform step 2 shortly as possible after step 1, since between the two steps new syncer connections that use the ‘old’ certificate will get rejected by the cluster that has
```suggestion
- Perform Step 2 as quickly as possible after performing Step 1.  Connections using the previous certificate are rejected by the new certificate.  Until both steps are performed, the database will be unable to sync.
```

2021-12-07 16:25 UTC, AlonMagrafta commented on content/rs/administering/cluster-operations/updating-certificates.md
> +- It is required that you perform step 2 shortly as possible after step 1, since between the two steps new syncer connections that use the ‘old’ certificate will get rejected by the cluster that has
```suggestion
- Perform Step 2 as quickly as possible after performing Step 1.  Connections using the previous certificate are rejected after applying the new certificate.  Until both steps are performed, recovery of the database sync cannot be established .
```

2021-12-07 17:24 UTC, lanceleonard approved these changes
LGTM

2021-12-07 17:24 UTC, lanceleonard commented on content/rs/administering/cluster-operations/updating-certificates.md
> +- **Step 2:** From the admin console, update the destination database (_replica_) configuration with the [new certificate]({{<relref "/administering/creating-databases/create-active-passive#configuri
```suggestion
- **Step 2:** From the admin console, update the destination database (_replica_) configuration with the [new certificate]({{<relref "rs/administering/creating-databases/create-active-passive#configuring-tls-for-replica-of-traffic-on-the-destination-database">}}).
```

2021-12-07 17:26 UTC, merged