typo
RedisLabs/redislabs-docs pull request #1736
Opened 2022-01-06 11:28 UTC by yorozen

raw.githubuser.com/RedisLabs/redis-enterprise-k8s-docs/master/openshift/scc.yaml
should be replaced by
github.com/RedisLabs/redis-enterprise-k8s-docs/master/openshift/scc.yaml

2022-01-06 15:28 UTC, rrelledge requested changes
When I try to use the new links, I get a "Not Found" error message.

2022-01-06 15:28 UTC, rrelledge commented on content/kubernetes/deployment/openshift/openshift-operatorhub.md
> +The constraint [scc.yaml](curl -O https://github.com/RedisLabs/redis-enterprise-k8s-docs/master/openshift/scc.yaml)
```suggestion
The constraint [scc.yaml](https://github.com/RedisLabs/redis-enterprise-k8s-docs/master/openshift/scc.yaml)
```

2022-01-06 18:34 UTC, kaitlynmichael reviewed
My subject matter experts told me that the raw url is required for curl commands. @yorozen what source are you getting this change from?

2022-02-02 00:56 UTC, kaitlynmichael commented
Closing due to lack of activity. As far as I have been able to research, the current text is correct.

2022-02-02 00:56 UTC, closed without merging