DOC-1131: RS - Arbel release note updates.
RedisLabs/redislabs-docs pull request #1778
Opened 2022-02-08 01:58 UTC by lanceleonard

- Initial draft

2022-02-08 02:02 UTC, lanceleonard commented
Staged previews are available: [v6.2.6.10 release notes](https://docs.redis.com/staging/jira-doc-1131/rs/release-notes/rs-6-2-10-february-2022/) & [v6.2.8 prerequisite updates](https://docs.redis.com/staging/jira-doc-1131/rs/release-notes/rs-6-2-8-october-2021/#prerequisites-and-notes).

2022-02-08 15:33 UTC, rrelledge commented on content/rs/release-notes/rs-6-2-10-february-2022.md
> +* Providing the MD5 value in the download center.
Is this repeated info?

2022-02-08 15:35 UTC, rrelledge commented on content/rs/release-notes/rs-6-2-10-february-2022.md
> +For seamless upgrade, the feature will be automatically enabled upon upgrade for replica-of and active-active TLS enabled target databases. We advise you to review and validate your certificates in y
```suggestion
For seamless upgrade, the feature will be automatically enabled upon upgrade for Replica-Of and Active-Active TLS-enabled target databases. We advise you to review and validate your certificates in your production environments and then to disable the feature via the API.
```

2022-02-08 16:45 UTC, lanceleonard commented on content/rs/release-notes/rs-6-2-10-february-2022.md
> +- RS66280 - Fixed the lexicographically [SORT](https://redis.io/commands/sort) command on Active-Active databases (e.g. `SORT mylist ALPHA`). The SORT command should only run on keys mapped to the sa
Fixed

2022-02-08 16:45 UTC, lanceleonard commented on content/rs/release-notes/rs-6-2-10-february-2022.md
> +For seamless upgrade, the feature will be automatically enabled upon upgrade for replica-of and active-active TLS enabled target databases. We advise you to review and validate your certificates in y
Fixed and reworked.

2022-02-08 16:45 UTC, lanceleonard commented on content/rs/release-notes/rs-6-2-10-february-2022.md
> +* Providing the MD5 value in the download center.
Fixed.

2022-02-13 09:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RedisLabs/redislabs-docs?pullRequest=1778) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/RedisLabs/redislabs-docs?pullRequest=1778) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: lanceleonard<br/>:x: adisht<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RedisLabs/redislabs-docs?pullRequest=1778) it.</sub>

2022-02-13 15:03 UTC, AlonMagrafta requested changes

2022-02-13 15:11 UTC, AlonMagrafta commented
@lanceleonard @adisht @rrelledge I've added my review + suggestion for the syncer bug. Please review.

2022-02-13 21:38 UTC, merged