DOC-1319 - RS Utilities Reorg: rladmin status page
RedisLabs/redislabs-docs pull request #1891
Opened 2022-04-25 20:39 UTC by cmilesb

Staging: https://docs.redis.com/staging/jira-doc-1319/rs/references/cli-utilities/rladmin/status/

2022-04-25 21:12 UTC, cmilesb commented on content/rs/references/cli-utilities/rladmin/status.md
> +NODE:ID ROLE   ADDRESS    EXTERNAL_ADDRESS HOSTNAME     MASTERS SLAVES OVERBOOKING_DEPTH SHARDS CORES FREE_RAM        PROVISIONAL_RAM VERSION   SHA    RACK-ID STATUS
```suggestion
NODE:ID ROLE   ADDRESS      EXTERNAL_ADDRESS HOSTNAME     MASTERS SLAVES OVERBOOKING_DEPTH SHARDS CORES FREE_RAM        PROVISIONAL_RAM VERSION   SHA    RACK-ID STATUS
```

2022-04-25 21:13 UTC, cmilesb commented on content/rs/references/cli-utilities/rladmin/status.md
> +NODE:ID ROLE   ADDRESS    EXTERNAL_ADDRESS HOSTNAME     MASTERS SLAVES OVERBOOKING_DEPTH SHARDS CORES FREE_RAM        PROVISIONAL_RAM VERSION   SHA    RACK-ID STATUS
```suggestion
NODE:ID ROLE   ADDRESS      EXTERNAL_ADDRESS HOSTNAME     MASTERS SLAVES OVERBOOKING_DEPTH SHARDS CORES FREE_RAM        PROVISIONAL_RAM VERSION   SHA    RACK-ID STATUS
```

2022-04-25 21:17 UTC, cmilesb commented on content/rs/references/cli-utilities/rladmin/status.md
> +| extra     | extra options that show more information |
```suggestion
| extra     | Extra options that show more information |
```

2022-04-25 21:17 UTC, cmilesb commented on content/rs/references/cli-utilities/rladmin/status.md
> +| extra <parameter> | extra options that show more information |
```suggestion
| extra <parameter> | Extra options that show more information |
```

2022-04-25 21:17 UTC, cmilesb commented on content/rs/references/cli-utilities/rladmin/status.md
> +| sort <column_titles> | sort results by specified column titles |
```suggestion
| sort <column_titles> | Sort results by specified column titles |
```

2022-04-25 21:18 UTC, cmilesb commented on content/rs/references/cli-utilities/rladmin/status.md
> +| extra <parameter> | extra options that show more information |
```suggestion
| extra <parameter> | Extra options that show more information |
```

2022-04-25 21:18 UTC, cmilesb commented on content/rs/references/cli-utilities/rladmin/status.md
> +| sort <column_titles> | sort results by specified column titles |
```suggestion
| sort <column_titles> | Sort results by specified column titles |
```

2022-04-25 21:19 UTC, cmilesb commented on content/rs/references/cli-utilities/rladmin/status.md
> +| extra <parameter> | extra options that show more information |
```suggestion
| extra <parameter> | Extra options that show more information |
```

2022-04-25 21:19 UTC, cmilesb commented on content/rs/references/cli-utilities/rladmin/status.md
> +| sort <column_titles> | sort results by specified column titles |
```suggestion
| sort <column_titles> | Sort results by specified column titles |
```

2022-04-25 21:19 UTC, cmilesb commented on content/rs/references/cli-utilities/rladmin/status.md
> +| extra <parameter> | extra options that show more information |
```suggestion
| extra <parameter> | Extra options that show more information |
```

2022-04-25 21:19 UTC, cmilesb commented on content/rs/references/cli-utilities/rladmin/status.md
> +| sort <column_titles> | sort results by specified column titles |
```suggestion
| sort <column_titles> | Sort results by specified column titles |
```

2022-04-25 21:21 UTC, rrelledge requested changes
Here are some initial suggestions.

2022-04-25 21:21 UTC, rrelledge commented on content/rs/references/cli-utilities/rladmin/status.md
> +| sort <column_titles> | sort results by specified column titles |
```suggestion
| node <id> | Only show endpoints for the specified node ID |
| extra <parameter> | Extra options that show more information |
| sort <column_titles> | Sort results by specified column titles |
```

2022-04-25 21:21 UTC, rrelledge commented on content/rs/references/cli-utilities/rladmin/status.md
> +db:3      database3        endpoint:3:1          node:3      single      N
```suggestion
db:3      database3        endpoint:3:1          node:3      single      No
```

2022-04-25 21:21 UTC, rrelledge commented on content/rs/references/cli-utilities/rladmin/status.md
> +If `issues_only` is specified, only instances that do not have an "OK" status are shown.
```suggestion
If `issues_only` is specified, it only shows shards that do not have an "OK" status.
```

2022-04-25 21:21 UTC, rrelledge commented on content/rs/references/cli-utilities/rladmin/status.md
> +If `issues_only` is specified, only instances that do not have an "OK" status are shown.
```suggestion
If `issues_only` is specified, it only shows databases that do not have an "OK" status.
```

2022-04-25 21:26 UTC, cmilesb commented on content/rs/references/cli-utilities/rladmin/status.md
> +| `extra` parameter | Description |
```suggestion
| Extra parameter | Description |
```

2022-04-25 21:59 UTC, rrelledge requested changes
Looks good! Here's a few more small suggestions.

2022-04-25 21:59 UTC, rrelledge commented on content/rs/references/cli-utilities/rladmin/status.md
> +        [ db <db:id | name> ]
```suggestion
        [ db {db:<id> | <name>} ]
```

2022-04-25 21:59 UTC, rrelledge commented on content/rs/references/cli-utilities/rladmin/status.md
> +| `extra` parameter | Description |
```suggestion
| Extra parameter | Description |
```

2022-04-25 21:59 UTC, rrelledge commented on content/rs/references/cli-utilities/rladmin/status.md
> +| `extra` parameter | Description |
```suggestion
| Extra parameter | Description |
```

2022-04-25 21:59 UTC, rrelledge commented on content/rs/references/cli-utilities/rladmin/status.md
> +| `extra` parameter | Description |
```suggestion
| Extra parameter | Description |
```

2022-04-26 19:39 UTC, rrelledge requested changes
I spotted a couple of options missing from the parameter tables.

2022-04-26 19:39 UTC, rrelledge commented on content/rs/references/cli-utilities/rladmin/status.md
> +| extra <parameter> | Extra options that show more information |
```suggestion
|-----------|-------------|
| node <id> | Only show endpoints for the specified node ID |
| extra <parameter> | Extra options that show more information |
```

2022-04-26 19:39 UTC, rrelledge commented on content/rs/references/cli-utilities/rladmin/status.md
> +| extra <parameter> | Extra options that show more information |
```suggestion
|-----------|-------------|
| node <id> | Only show shards for the specified node ID |
| db db:<id> | Only show shards for the specified database ID |
| db <name> | Only show shards for the specified database name |
| extra <parameter> | Extra options that show more information |
```

2022-04-26 21:19 UTC, rrelledge approved these changes
Looks good to me.

2022-04-27 13:58 UTC, merged