DOC-1328 - RS CLI Utilities Reorg: rladmin restart page
RedisLabs/redislabs-docs pull request #1902
Opened 2022-04-29 18:20 UTC by cmilesb

Staging Link: https://docs.redis.com/staging/jira-doc-1328/rs/references/cli-utilities/rladmin/restart/

2022-05-02 17:39 UTC, kaitlynmichael requested changes
Left a few wording changes for clarity. Just remember that we always(there are exceptions of course) should to refer to the RS product as it's full name Redis Enterprise Software.

2022-05-02 17:39 UTC, kaitlynmichael commented on content/rs/references/cli-utilities/rladmin/restart.md
> +description: Restarts the Redis software instance for a specific database.
```suggestion
description: Restarts the Redis Enterprise Software instance for a specific database.
```

2022-05-02 17:39 UTC, kaitlynmichael commented on content/rs/references/cli-utilities/rladmin/restart.md
> +`rladmin restart` restarts the Redis software in use by a specific database
```suggestion
`rladmin restart` restarts the Redis Enterprise Software instance for a specific database by scheduling a restart of the primary and replica processes.
```

2022-05-02 17:39 UTC, kaitlynmichael commented on content/rs/references/cli-utilities/rladmin/restart.md
> +`Done` if the restart completed successfully, `ERROR` otherwise.
```suggestion
Returns `Done` if the restart completed successfully, `ERROR` otherwise.
```

2022-05-03 16:25 UTC, rrelledge requested changes
Looks good so far. I've left a couple of suggestions.

2022-05-03 16:25 UTC, rrelledge commented on content/rs/references/cli-utilities/rladmin/restart.md
> +`rladmin restart` restarts the Redis Enterprise Software instance for a specific database by scheduling a restart of the primary and replica processes.
```suggestion
`rladmin restart` schedules a restart of the Redis Enterprise Software processes on primary and replica instances of a specific database.
```

2022-05-03 16:25 UTC, rrelledge commented on content/rs/references/cli-utilities/rladmin/restart.md
> +rladmin restart db { db:id | name }
```suggestion
rladmin restart db { db:<id> | <name> }
```

2022-05-03 16:25 UTC, rrelledge commented on content/rs/references/cli-utilities/rladmin/restart.md
> +| db             | db:\<id\><br /> name           | Restarts the Redis Software for the specified database                |
```suggestion
| db             | db:\<id\><br /> name           | Restarts Redis Enterprise Software processes for the specified database                |
```

2022-05-03 16:25 UTC, rrelledge commented on content/rs/references/cli-utilities/rladmin/restart.md
> +Returns `Done` if the restart completed successfully, `ERROR` otherwise.
```suggestion
Returns `Done` if the restart completed successfully. Otherwise, it returns `ERROR`.
```

2022-05-03 16:25 UTC, rrelledge commented on content/rs/references/cli-utilities/rladmin/restart.md
> +description: Restarts the Redis Enterprise Software instance for a specific database.
```suggestion
description: Restarts Redis Enterprise Software processes for a specific database.
```

2022-05-03 18:40 UTC, rrelledge approved these changes
Looks good to me.

2022-05-03 18:54 UTC, merged