DOC-1050: RedisJSON Quick Start Rewrite
RedisLabs/redislabs-docs pull request #1908
Opened 2022-05-05 15:43 UTC by cmilesb

Staging link: https://docs.redis.com/staging/jira-doc-1050/modules/redisjson/redisjson-quickstart/

Still working on the Python example, and probably could use a reorg or changing the examples.

2022-05-05 20:58 UTC, rrelledge requested changes
Nice updates! This looks good to me. I just left some small suggestions.

2022-05-05 20:58 UTC, rrelledge commented on content/modules/redisjson/redisjson-quickstart.md
> +The `redis-cli` command line tool comes packaged with Redis. You can use it to connect to your Redis database and test the following RedisJSON commands.
```suggestion
The [`redis-cli`](https://redis.io/docs/manual/cli/) command line tool comes packaged with Redis. You can use it to connect to your Redis database and test the following RedisJSON commands.
```

2022-05-05 20:58 UTC, rrelledge commented on content/modules/redisjson/redisjson-quickstart.md
> +If you want to use RediSearch within an application, you can use one of these [client libraries](https://redis.io/docs/stack/json/clients/).
```suggestion
If you want to use RedisJSON within an application, you can use one of these [client libraries](https://redis.io/docs/stack/json/clients/).
```

2022-05-05 20:58 UTC, rrelledge commented on content/modules/redisjson/redisjson-quickstart.md
> +Use `JSON.TYPE` to check the JSON type of the key, or an entity inside the key.
```suggestion
Use `JSON.TYPE` to check the JSON type of the key or an entity inside the key.
```

2022-05-05 20:58 UTC, rrelledge commented on content/modules/redisjson/redisjson-quickstart.md
> +# Adding info to the JSON document
```suggestion
# Add info to the JSON document
```

2022-05-05 20:58 UTC, rrelledge commented on content/modules/redisjson/redisjson-quickstart.md
> +# Adding new items to the list
```suggestion
# Add new items to the list
```

2022-05-05 20:58 UTC, rrelledge commented on content/modules/redisjson/redisjson-quickstart.md
> +# Incrementing numerical values
```suggestion
# Increment item counts
```

2022-05-05 20:58 UTC, rrelledge commented on content/modules/redisjson/redisjson-quickstart.md
> +# Getting all items no matter which heading they're under
```suggestion
# Get all items no matter which heading they're under
```

2022-05-05 20:58 UTC, rrelledge commented on content/modules/redisjson/redisjson-quickstart.md
> +# Deleting portions of the document
```suggestion
# Delete specific parts of the document
```

2022-05-05 20:58 UTC, rrelledge commented on content/modules/redisjson/redisjson-quickstart.md
> +# Deleting the key
```suggestion
# Delete the JSON document key
```

2022-05-05 20:58 UTC, rrelledge commented on content/modules/redisjson/redisjson-quickstart.md
> +Creating Shopping list...
```suggestion
Creating shopping list...
```

2022-05-05 20:58 UTC, rrelledge commented on content/modules/redisjson/redisjson-quickstart.md
> +print("Creating Shopping list...")
```suggestion
print("Creating shopping list...")
```

2022-05-05 21:49 UTC, nermiller approved these changes
LGTM, with just a couple of minor edits. Such nice work, Cameron!

2022-05-05 21:49 UTC, nermiller commented on content/modules/redisjson/redisjson-quickstart.md
> +The `redis-cli` command line tool comes packaged with Redis. You can use it to connect to your Redis database and test the following RedisJSON commands.
```suggestion
The [`redis-cli`](https://redis.io/docs/manual/cli/) command-line tool is part of the Redis installation. You can use it to connect to your Redis database and test RedisJSON commands.
```

2022-05-05 21:49 UTC, nermiller commented on content/modules/redisjson/redisjson-quickstart.md
> +If you want to use RediSearch within an application, you can use one of these [client libraries](https://redis.io/docs/stack/json/clients/).
```suggestion
If you want to use RedisJSON within an application, you can use one of the [client libraries](https://redis.io/docs/stack/json/clients/).
```

2022-05-06 16:43 UTC, rrelledge approved these changes
Looks good to me.

2022-05-06 16:44 UTC, merged