DOC-1325: RS CLI Reorg: rladmin node
RedisLabs/redislabs-docs pull request #1920
Opened 2022-05-12 14:49 UTC by cmilesb

Staging link: https://docs.redis.com/staging/jira-doc-1325/rs/references/cli-utilities/rladmin/node/

Still working on the individual command pages.

2022-05-12 15:32 UTC, nermiller approved these changes
LGTM with minor suggestions

2022-05-12 15:32 UTC, nermiller commented on content/rs/references/cli-utilities/rladmin/node/addr.md
> +Use [`rladmin status nodes`]({{<relref "/rs/references/cli-utilities/rladmin/status#status-nodes">}}) to verify the internal IP address was changed.
Consider starting with action first, i.e. "Verify that the internal IP address has changed, ..."

2022-05-12 15:32 UTC, nermiller commented on content/rs/references/cli-utilities/rladmin/node/addr.md
> +`rladmin node addr set` sets the internal IP address of a node. The internal IP address can only be set with `rladmin node addr` when the node is down.
```suggestion
`rladmin node addr set` sets the internal IP address of a node. You can set the internal IP address using `rladmin node addr` only when the node is down.
```

2022-05-13 20:09 UTC, rrelledge requested changes
These are looking good! I left some suggestions for changes.

2022-05-13 20:09 UTC, rrelledge commented on content/rs/references/cli-utilities/rladmin/node/addr.md
> +| ip_addr   | IP address                     | Sets specified IP address as the internal IP of the node                                      |
```suggestion
| node      | integer                        | Sets the internal IP address of the specified node                                                |
| ip_addr   | IP address                     | Sets the node's internal IP address to the specified IP address                                      |
```

2022-05-13 20:09 UTC, rrelledge commented on content/rs/references/cli-utilities/rladmin/node/enslave.md
> +| retry_timeout_seconds | integer                        | Retries any failures until the specified number of seconds has passed.                    |
```suggestion
| retry_timeout_seconds | integer                        | Retries on failure until the specified number of seconds has passed.                    |
```

2022-05-13 20:09 UTC, rrelledge commented on content/rs/references/cli-utilities/rladmin/node/enslave.md
> +| retry_timeout_seconds | integer                        | Retries any failures until the specified number of seconds has passed.                    |
```suggestion
| retry_timeout_seconds | integer                        | Retries on failure until the specified number of seconds has passed.                    |
```

2022-05-13 20:09 UTC, rrelledge commented on content/rs/references/cli-utilities/rladmin/node/enslave.md
> +| retry_timeout_seconds | integer                        | Retries any failures until the specified number of seconds has passed.                    |
```suggestion
| retry_timeout_seconds | integer                        | Retries on failure until the specified number of seconds has passed.                    |
```

2022-05-13 20:09 UTC, rrelledge commented on content/rs/references/cli-utilities/rladmin/node/enslave.md
> +                [retry_timeout_seconds]
`retry_timeout_seconds` accepts an integer, right? If so, the other two commands need to be updated too.
```suggestion
                [retry_timeout_seconds] <seconds>
```

2022-05-13 21:09 UTC, rrelledge approved these changes
Looks good to me.

2022-05-13 21:10 UTC, merged