DOC-1415: Identify existing REST API Examples in RS docs and simplify the presentation
RedisLabs/redislabs-docs pull request #1938
Opened 2022-05-23 19:56 UTC by cmilesb

Staging Link: https://docs.redis.com/staging/jira-doc-1415/rs/

Part of the RS REST API Cleanup. Changed any REST API examples in /rs/ from cURL examples to "VERB https://[host][:port]/v1/[endpoint]".

Did not touch any calls in the user security page, per Lance.

2022-05-24 22:06 UTC, rrelledge requested changes
This looks good so far. I left a couple of initial suggestions. One more thing you might consider is adding some links to the relevant REST API request pages.

2022-05-25 20:51 UTC, rrelledge reviewed
Here's a few more suggestions.

2022-05-25 20:51 UTC, rrelledge commented on content/rs/administering/cluster-operations/removing-node.md
> +To remove a node using the REST API, use the [`/v1/nodes/node_id/actions/remove`]({{< relref "/rs/references/rest-api/requests/nodes/actions#post-node-action" >}}) endpoint with the JSON data and the
```suggestion
To remove a node using the REST API, use the [`/v1/nodes/<node_id>/actions/remove`]({{< relref "/rs/references/rest-api/requests/nodes/actions#post-node-action" >}}) endpoint with the JSON data and the "Content-Type: application/json" header.
```

2022-05-25 20:51 UTC, rrelledge commented on content/rs/administering/access-control/password-rotation.md
> +1. Delete the original password with [`DELETE v1/users/password`]({{< relref "/rs/references/rest-api/requests/users/password#delete-password" >}}):
```suggestion
1. Delete the original password with [`DELETE /v1/users/password`]({{< relref "/rs/references/rest-api/requests/users/password#delete-password" >}}):
```

2022-05-25 20:51 UTC, rrelledge commented on content/rs/administering/troubleshooting/disabling-services.md
> +After you turn off a service, you can re-enable in the same way.
```suggestion
In a deployment with limited memory resources, you can use the REST API or `rladmin` to turn off certain services to free system memory.
Before you turn off a service, make sure that your deployment does not depend on that service.
After you turn off a service, you can re-enable it in the same way.
```

2022-05-25 20:51 UTC, rrelledge commented on content/rs/databases/import-export/flush-db-crdb.md
> +        PUT https://[host][:port]/v1/crdbs/guid/flush
```suggestion
        PUT https://[host][:port]/v1/crdbs/<guid>/flush
```

2022-06-22 20:17 UTC, cmilesb commented
Opened a new PR for this issue - #2004 - to bring in changes from the RS reorg.

2022-06-22 20:17 UTC, closed without merging