DOC-842: RC Reorg - Rework Admin menu, part II
RedisLabs/redislabs-docs pull request #2072
Opened 2022-08-04 17:01 UTC by lanceleonard

- Initial draft

2022-08-04 18:32 UTC, lanceleonard commented
A staged preview [is available](https://docs.redis.com/staging/jira-doc-842-ii/rc/databases/).

2022-08-04 21:07 UTC, rrelledge requested changes
Looks good to me aside from the small alias change I left a suggestion for.

2022-08-04 21:07 UTC, rrelledge commented on content/rc/databases/system-logs.md
> +           "rc/administration/system-logs.md" ]
```suggestion
           "/rc/administration/system-logs/",
           "/rc/administration/system-logs.md" ]
```

2022-08-05 13:09 UTC, lanceleonard commented on content/rc/databases/system-logs.md
> +           "rc/administration/system-logs.md" ]
Fixed

2022-08-05 14:04 UTC, rrelledge approved these changes

2022-08-05 14:49 UTC, merged