DOC-1562: RC - Fix broken image in API System Logs example
RedisLabs/redislabs-docs pull request #2090
Opened 2022-08-12 10:37 UTC by lanceleonard

- Initial draft

2022-08-12 10:39 UTC, lanceleonard commented
A staged preview [is available](https://docs.redis.com/staging/jira-doc-1562/rc/api/examples/audit-system-logs/).

2022-08-12 13:50 UTC, rrelledge requested changes
Looks good to me aside from the admin console link. I left a couple of other small suggestions.

2022-08-12 13:50 UTC, rrelledge commented on content/rc/api/examples/audit-system-logs.md
> +To view the log, sign into the Redis Cloud [admin console]() and then select Logs from the main menu.
```suggestion
To view the log, sign in to the Redis Cloud [admin console](https://app.redislabs.com/) and then select **Logs** from the main menu.
```

2022-08-12 13:50 UTC, rrelledge commented on content/rc/databases/system-logs.md
> +* Use the **Export all** button to export all logs as a comma-separated, variable text (CSV) file for use in other systems and programs.
```suggestion
* Use the **Export all** button to export all logs as a comma-separated values (CSV) file for use in other systems and programs.
```

2022-08-15 17:02 UTC, lanceleonard commented on content/rc/databases/system-logs.md
> +* Use the **Export all** button to export all logs as a comma-separated, variable text (CSV) file for use in other systems and programs.
Fixed.

2022-08-15 17:02 UTC, lanceleonard commented on content/rc/api/examples/audit-system-logs.md
> +To view the log, sign into the Redis Cloud [admin console]() and then select Logs from the main menu.
Fixed.

2022-08-15 17:06 UTC, rrelledge approved these changes

2022-08-15 17:07 UTC, merged