DOC-1433: Add Cloud API examples for managing a subscription in API "Create and edit subscriptions" page
RedisLabs/redislabs-docs pull request #2155
Opened 2022-09-20 17:53 UTC by cmilesb

Staging link: https://docs.redis.com/staging/jira-doc-1433/rc/api/examples/manage-subscriptions/

2022-09-21 19:26 UTC, kaitlynmichael requested changes
Left some suggestions to tighten up the wording. Let me know if you have any questions :)

2022-09-21 19:26 UTC, kaitlynmichael commented on content/rc/api/examples/manage-subscriptions.md
> +The Redis Enterprise Cloud REST API allows you to create and manage a subscription.
I would avoid "allows you to". You could either start with the verb: 
Create and manage your subscription with the Redis Enterprise Cloud REST API. 
or use "lets" 
The Redis Enterprise Cloud REST API lets you create and manage your subscription.

2022-09-21 19:26 UTC, kaitlynmichael commented on content/rc/api/examples/manage-subscriptions.md
> +To use the sample JSON document in your own account, modify these parameters:
I would start this with the action: 
Modify the [following/these] parameters in the sample JSON document to create a subscription on your own account.

2022-09-21 19:26 UTC, kaitlynmichael commented on content/rc/api/examples/manage-subscriptions.md
> +- **`paymentMethodId`** - Specify a payment method that is connected to your account.
I would say either: 
...connected to your account. 
or
...for your account.
"that is connected to" is too many words

2022-09-21 19:26 UTC, kaitlynmichael commented on content/rc/api/examples/manage-subscriptions.md
> +- **`cloudAccountId`** - Set a cloud account ID that is connected to your account.
"that is connected to" -> same comment as above

2022-09-21 19:26 UTC, kaitlynmichael commented on content/rc/api/examples/manage-subscriptions.md
> +The response body contains the `taskId` of the task that is creating the subscription. You can use `GET /v1/tasks/<taskId>` to track the status of this task.
```suggestion
The response body contains the `taskId` for the task creating the subscription. You can use `GET /v1/tasks/<taskId>` to track the status of this task.
```

2022-09-21 19:26 UTC, kaitlynmichael commented on content/rc/api/examples/manage-subscriptions.md
> +The response body contains the `taskId` of the task that is updating the subscription. You can use `GET /v1/tasks/<taskId>` to track the status of this task.
```suggestion
The response body contains the `taskId` for the task updating the subscription. You can use `GET /v1/tasks/<taskId>` to track the status of this task.
```

2022-09-21 19:26 UTC, kaitlynmichael commented on content/rc/api/examples/manage-subscriptions.md
> +- **`paymentMethodId`** - Specify a different payment method that is defined for your account.
```suggestion
- **`paymentMethodId`** - Specify a different payment method for your account.
```

2022-09-21 19:26 UTC, kaitlynmichael commented on content/rc/api/examples/manage-subscriptions.md
> +The response body contains the `taskId` of the task that is deleting the subscription. You can use `GET /v1/tasks/<taskId>` to track the status of this task.
```suggestion
The response body contains the `taskId` for the task deleting the subscription. You can use `GET /v1/tasks/<taskId>` to track the status of this task.
```

2022-09-21 19:26 UTC, kaitlynmichael commented on content/rc/api/examples/manage-subscriptions.md
> +    You do not need to pass this field in your API request if you subscribed to Redis Enterprise Cloud through GCP Marketplace.
```suggestion
    You don't need to pass this field in your API request if you subscribed through GCP Marketplace.
```

2022-09-21 19:26 UTC, kaitlynmichael commented on content/rc/api/examples/manage-subscriptions.md
> +    You can look up cloud account IDs using `GET /cloud-accounts`. To use internal resources, set it to `"cloudAccountId": 1`.
```suggestion
    To list cloud account IDs, use `GET /cloud-accounts`. 
    To use internal resources, set `cloudAccountID` to`"cloudAccountId": 1`.
```

2022-09-21 19:26 UTC, kaitlynmichael commented on content/rc/api/examples/manage-subscriptions.md
> +    If you subscribed to Redis Enterprise Cloud through GCP Marketplace, use `1` for this field.
```suggestion
    If you subscribed through GCP Marketplace, use `1` for this field.
```

2022-09-21 19:26 UTC, kaitlynmichael commented on content/rc/api/examples/manage-subscriptions.md
> +The request JSON body contains two primary segments: subscription specification and databases specification. When you create a subscription, you must specify one or more databases in the "`databases`
```suggestion
The request JSON body contains two segments: subscription specification and databases specification. When you create a subscription, you must specify one or more databases in the "`databases`" array.
```

2022-09-21 19:26 UTC, kaitlynmichael commented on content/rc/api/examples/manage-subscriptions.md
> +    You can look up a payment method identifier using the `GET /payment-methods` API operation.
To find the IDs for payment methods connected to your account, use he `GET /payment-methods` API operation.

2022-09-28 16:07 UTC, rrelledge approved these changes
Looks good to me. I left a few suggestions for you to consider. Also, should the examples show [host]:[port]?

2022-09-28 16:07 UTC, rrelledge commented on content/rc/api/examples/manage-subscriptions.md
> +The response body contains the `taskId` for the task deleting the subscription. You can use `GET /v1/tasks/<taskId>` to track the status of this task.
```suggestion
The response body contains the `taskId` for the task that deletes the subscription. You can use `GET /v1/tasks/<taskId>` to track the task's status.
```

2022-09-28 16:07 UTC, rrelledge commented on content/rc/api/examples/manage-subscriptions.md
> +Modify the following parameters in the sample JSON document to create a subscription on your own account.
```suggestion
Modify the following parameters in the sample JSON document to create a subscription on your own account:
```

2022-09-28 16:37 UTC, merged