DOC-1737: RC: Connection Wizard
RedisLabs/redislabs-docs pull request #2211
Opened 2022-10-26 17:46 UTC by cmilesb

Staging link: https://docs.redis.com/staging/preview-rc-connect/rc/rc-quickstart/

2022-11-02 15:49 UTC, cmilesb commented
Opening PR for merge on GA date for connection Wizard.

2022-11-03 20:18 UTC, kaitlynmichael requested changes
Left some suggestions for tightening up wording.

2022-11-03 20:18 UTC, kaitlynmichael commented on content/rc/rc-quickstart.md
> +Once you have the username and password, select the **Connect** button to open the connection wizard.
```suggestion
Once you have the username and password, select **Connect** to open the connection wizard.
```

2022-11-03 20:18 UTC, kaitlynmichael commented on content/rc/rc-quickstart.md
> +The connection wizard shows how to connect to your database with the following methods:
```suggestion
The connection wizard provides the following database connection methods:
```

2022-11-03 20:18 UTC, kaitlynmichael commented on content/rc/rc-quickstart.md
>  - Using the `redis-cli` utility
```suggestion
- redis-cli` utility
```

2022-11-03 20:18 UTC, kaitlynmichael commented on content/rc/rc-quickstart.md
> +- Using a [Redis client](https://redis.io/clients) for your preferred programming language
```suggestion
- [Redis client](https://redis.io/clients) for your preferred programming language
```

2022-11-03 20:18 UTC, kaitlynmichael commented on content/rc/rc-quickstart.md
> +- Using [RedisInsight](https://redis.com/redis-enterprise/redis-insight/)
```suggestion
- [RedisInsight](https://redis.com/redis-enterprise/redis-insight/)
```

2022-11-03 20:18 UTC, kaitlynmichael commented on content/rc/rc-quickstart.md
> +Here's how to connect to your database using the [redis-py](https://github.com/redis/redis-py#redis-py) library for Python.
```suggestion
To connect to your database using the [redis-py](https://github.com/redis/redis-py#redis-py) library for Python:
```

2022-11-03 20:18 UTC, kaitlynmichael commented on content/rc/rc-quickstart.md
> +1. After you install and open RedisInsight, select **Add Redis Database**.
```suggestion
1. Open RedisInsight and select **Add Redis Database**.
```

2022-11-03 20:18 UTC, kaitlynmichael commented on content/rc/rc-quickstart.md
> +1. In RedisInsight, enter the copied connection information into the **Host** field. RedisInsight automatically populates the rest of the fields needed to connect to the database as the default user.
```suggestion
1. In RedisInsight, paste the connection information into the **Host** field. 
  RedisInsight automatically populates the rest of the fields needed to connect to the database as the default user.
```
Add the second sentence as an indented line below the step.

2022-11-03 20:18 UTC, kaitlynmichael commented on content/rc/rc-quickstart.md
> +4. Add the copied code to your program and replace `<username>` and `<password>` with your username and password.
```suggestion
4. Paste the code to your program and replace `<username>` and `<password>` with your username and password.
```

2022-11-04 16:30 UTC, kaitlynmichael approved these changes

2022-11-06 19:27 UTC, merged