supported modules on AA
RedisLabs/redislabs-docs pull request #2247
Opened 2022-11-21 18:01 UTC by AlonMagrafta

2022-11-21 18:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RedisLabs/redislabs-docs?pullRequest=2247) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RedisLabs/redislabs-docs?pullRequest=2247) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RedisLabs/redislabs-docs?pullRequest=2247) it.</sub>

2022-11-21 18:40 UTC, kaitlynmichael requested changes
I reworded a bit for clarity. Once you approve those changes I can push this out.

2022-11-21 18:40 UTC, kaitlynmichael commented on content/rs/release-notes/rs-6-2-18.md
> +The capability of indexing, query and full-text search of nested JSON documents are now also GA on Active-Active (achieved by the combination of RedisJSON with RediSearch).
```suggestion
Index, query, and full-text search of nested JSON documents are now available on Active-Active  databases by using the combination of RedisJSON with RediSearch.
```

2022-11-21 18:40 UTC, kaitlynmichael commented on content/rs/databases/active-active/planning.md
> +Starting v6.2.18 the capability of indexing, query and full-text search of nested JSON documents are now also GA on Active-Active (achieved by the combination of RedisJSON with RediSearch).
```suggestion
Starting v6.2.18 the capability of index, query, and full-text search of nested JSON documents, are now also available for Active-Active databases by using a combination of RedisJSON with RediSearch.
```

2022-11-21 18:55 UTC, AlonMagrafta commented
Thanks @kaitlynmichael

2022-11-21 18:55 UTC, lanceleonard approved these changes

2022-11-21 18:55 UTC, lanceleonard commented on content/rs/databases/active-active/planning.md
> +Starting v6.2.18 the capability of index, query, and full-text search of nested JSON documents, are now also available for Active-Active databases by using a combination of RedisJSON with RediSearch.
```suggestion
Starting with v6.2.18, you can now index, query, and perform full-text searches of nested JSON documents in Active-Activate databases, by combining RedisJSON and RediSearch.
```

2022-11-21 18:55 UTC, lanceleonard commented on content/rs/release-notes/rs-6-2-18.md
> +Index, query, and full-text search of nested JSON documents are now available on Active-Active  databases by using the combination of RedisJSON with RediSearch.
```suggestion
Active-Active databases now support Index, query, and full-text search of nested JSON documents when combining RedisJSON with RediSearch.
```

2022-11-21 18:55 UTC, lanceleonard commented on content/rs/release-notes/rs-6-2-18.md
> +Find out more about [`Active-Active with RedisJSON`]({{<relref "//modules/redisjson/active-active">}})
```suggestion
To learn more, see  [`Active-Active with RedisJSON`]({{<relref "//modules/redisjson/active-active">}}).
```

2022-11-21 19:06 UTC, rrelledge commented on content/rs/databases/active-active/planning.md
> +Starting with v6.2.18, you can now index, query, and perform full-text searches of nested JSON documents in Active-Activate databases, by combining RedisJSON and RediSearch.
Noticed a typo.
```suggestion
Starting with v6.2.18, you can index, query, and perform full-text searches of nested JSON documents in Active-Active databases by combining RedisJSON and RediSearch.
```

2022-11-22 07:47 UTC, AlonMagrafta commented
@kaitlynmichael @lanceleonard can we push? I see there is still change request by Kaitlyn - do we have open items?

2022-11-23 14:36 UTC, merged