DOC-1822: Edit mailing/billing address UX changes
RedisLabs/redislabs-docs pull request #2376
Opened 2023-02-22 00:03 UTC by cmilesb

Staged links: 
https://docs.redis.com/staging/jira-doc-1822/rc/accounts/account-settings/
https://docs.redis.com/staging/jira-doc-1822/rc/billing-and-payments/

2023-02-23 16:56 UTC, kaitlynmichael approved these changes
Great job! Very clear. I added some suggestions to shorten the language or change to active voice.

2023-02-23 16:56 UTC, kaitlynmichael commented on content/rc/billing-and-payments.md
> +To edit the account billing address:
```suggestion
To edit the Redis Cloud account billing address:
```

2023-02-23 16:56 UTC, kaitlynmichael commented on content/rc/billing-and-payments.md
> +1. In the Redis Cloud [admin portal](https://app.redislabs.com/), select **Billing & Payments** and then select the **Payment Methods** tab.
Another options for these types of steps 

```suggestion
1. In the Redis Cloud [admin portal](https://app.redislabs.com/), select **Billing & Payments** > **Payment Methods**.
```

2023-02-23 16:56 UTC, kaitlynmichael commented on content/rc/billing-and-payments.md
> +2. Select the **Credit Card options** menu and select **Edit billing address**.
Same type of suggestion to cut length as above: 
```suggestion
2. Select **Credit Card options** > **Edit billing address**.
```

2023-02-23 16:56 UTC, kaitlynmichael commented on content/rc/billing-and-payments.md
> +Changing the billing address to your account will remove any payment methods associated with the old billing address. See [Add payment method](#add-payment-method) to learn how to add a payment metho
```suggestion
Changing the billing address for your account will remove any payment methods associated with the old billing address. See [Add payment method](#add-payment-method) to learn how to add a payment method back to your account.
```

2023-02-23 16:56 UTC, kaitlynmichael commented on content/rc/billing-and-payments.md
> +1. In the Redis Cloud [admin portal](https://app.redislabs.com/), select **Billing & Payments** and then select the **Payment Methods** tab.
```suggestion
1. In the Redis Cloud [admin portal](https://app.redislabs.com/), select **Billing & Payments** > **Payment Methods** .
```

2023-02-23 16:56 UTC, kaitlynmichael commented on content/rc/billing-and-payments.md
> +2. Select the **Credit Card options** menu and select **Edit mailing address**.
```suggestion
2. Select  **Credit Card options** > **Edit mailing address**.
```

2023-02-23 16:56 UTC, kaitlynmichael commented on content/rc/billing-and-payments.md
> +1. In the Redis Cloud [admin portal](https://app.redislabs.com/), select **Billing & Payments** and then select the **Credits** tab.
```suggestion
1. In the Redis Cloud [admin portal](https://app.redislabs.com/), select **Billing & Payments** > **Credits**.
```

2023-02-23 16:56 UTC, kaitlynmichael commented on content/rc/billing-and-payments.md
> +2.  Enter the coupon code and then select the **Apply** button.
```suggestion
2.  Enter the coupon code and select the **Apply** button.
```

2023-02-23 16:56 UTC, kaitlynmichael commented on content/rc/billing-and-payments.md
> +1. In the Redis Cloud [admin portal](https://app.redislabs.com/), select **Billing & Payments** and then make sure the Billing History tab is selected.
```suggestion
1. In the Redis Cloud [admin portal](https://app.redislabs.com/), select **Billing & Payments** and make sure the Billing History tab is selected.
```

2023-02-23 16:56 UTC, kaitlynmichael commented on content/rc/billing-and-payments.md
> +1. In the Redis Cloud [admin portal](https://app.redislabs.com/), select **Billing & Payments** and then select the **Payment Methods** tab.
```suggestion
1. In the Redis Cloud [admin portal](https://app.redislabs.com/), select **Billing & Payments** > **Payment Methods** .
```

2023-02-23 16:56 UTC, kaitlynmichael commented on content/rc/billing-and-payments.md
> +2.  Select **Add credit card** and then provide the details.
```suggestion
2.  Select **Add credit card** and add the credit card details.
```

2023-02-23 16:56 UTC, kaitlynmichael commented on content/rc/billing-and-payments.md
> +    The value of the coupon is applied to your account when accepted.
```suggestion
    The value of the coupon applies to your account when accepted.  
```

2023-02-23 16:56 UTC, kaitlynmichael commented on content/rc/billing-and-payments.md
> +    The value of the coupon is applied to your account when accepted.
Active voice change

2023-02-23 17:10 UTC, rrelledge commented on content/rc/billing-and-payments.md
> +1. In the Redis Cloud [admin portal](https://app.redislabs.com/), select **Billing & Payments** and then make sure the Billing History tab is selected.
```suggestion
1. In the Redis Cloud [admin console](https://app.redislabs.com/), select **Billing & Payments > Billing History**.
```

Or you could remove the "Billing History" part and just specify this tab in the next step:

```suggestion
1. In the Redis Cloud [admin console](https://app.redislabs.com/), select **Billing & Payments**.
```

2023-02-23 17:13 UTC, rrelledge commented on content/rc/billing-and-payments.md
> +2.  Locate and select the invoice.
If you choose to remove "Billing History" from the previous step:
```suggestion
2.  From the **Billing History** tab, locate and select the invoice.
```

2023-02-23 17:14 UTC, rrelledge commented on content/rc/billing-and-payments.md
> +1. In the Redis Cloud [admin portal](https://app.redislabs.com/), select **Billing & Payments** and then select the **Payment Methods** tab.
```suggestion
1. In the Redis Cloud [admin console](https://app.redislabs.com/), select **Billing & Payments** and then select the **Payment Methods** tab.
```

2023-02-23 17:16 UTC, rrelledge commented on content/rc/billing-and-payments.md
> +1. In the Redis Cloud [admin portal](https://app.redislabs.com/), select **Billing & Payments** and then select the **Payment Methods** tab.
```suggestion
1. In the Redis Cloud [admin console](https://app.redislabs.com/), select **Billing & Payments** and then select the **Payment Methods** tab.
```

2023-02-23 17:17 UTC, rrelledge commented on content/rc/billing-and-payments.md
> +1. In the Redis Cloud [admin portal](https://app.redislabs.com/), select **Billing & Payments** and then select the **Payment Methods** tab.
```suggestion
1. In the Redis Cloud [admin console](https://app.redislabs.com/), select **Billing & Payments** and then select the **Payment Methods** tab.
```

2023-02-23 17:17 UTC, rrelledge commented on content/rc/billing-and-payments.md
> +1. In the Redis Cloud [admin portal](https://app.redislabs.com/), select **Billing & Payments** and then select the **Credits** tab.
```suggestion
1. In the Redis Cloud [admin console](https://app.redislabs.com/), select **Billing & Payments** and then select the **Credits** tab.
```

2023-02-23 17:47 UTC, rrelledge requested changes
Oh, I also noticed a broken image that needs to be fixed.

2023-02-23 17:47 UTC, rrelledge commented on content/rc/accounts/account-settings.md
> +   {{<image filename="images/rc/account-settings-edit-address-button.png" alt="Select the Edit button to change the account's billing addresss." width="75%">}}{{< /image >}}
This image is broken. Looks like there is a typo in the actual filename: an extra "d" in "address".
```suggestion
   {{<image filename="images/rc/account-settings-edit-address-button.png" alt="Select the Edit button to change the account's billing address." width="75%">}}{{< /image >}}
```

2023-02-23 17:47 UTC, rrelledge commented on content/rc/billing-and-payments.md
> +4.  Select the **Add Credit Card** button to save your changes.
```suggestion
4.  Select the **Add credit card** button to save your changes.
```

2023-02-23 17:47 UTC, rrelledge commented on content/rc/billing-and-payments.md
> +2. Select the **Credit Card options** menu and select **Edit billing address**.
```suggestion
2. Select the **Credit card options** menu and select **Edit billing address**.
```

2023-02-23 17:47 UTC, rrelledge commented on content/rc/billing-and-payments.md
> +2. Select the **Credit Card options** menu and select **Edit mailing address**.
```suggestion
2. Select the **Credit card options** menu and select **Edit mailing address**.
```

2023-02-27 22:49 UTC, rrelledge approved these changes
Looks good to me!

2023-03-06 16:01 UTC, merged