DOC-2069 AA preview content fixes
RedisLabs/redislabs-docs pull request #2465
Opened 2023-03-28 21:27 UTC by kaitlynmichael

Jira: https://redislabs.atlassian.net/browse/DOC-2069
Staged preview: staging-DOC-2069

2023-03-29 07:26 UTC, alon-zada requested changes
Great!
please view one comment.

2023-03-29 07:26 UTC, alon-zada commented on content/kubernetes/active-active/preview/create-reaadb.md
>      spec:
imo we should also include the '.spec.databaseSecretName' that sets the AA database password, we are thinking that this should be recommendation (currently this example will create AA DB without password and it is not a good practice), maybe adding a note that this is example w/o the database secret and directing to "how to set database secret" instructions - wdyt?.

2023-03-30 04:02 UTC, nermiller approved these changes

2023-03-30 15:04 UTC, alon-zada approved these changes
Great!
please view one small comment.

2023-03-30 15:04 UTC, alon-zada commented on content/kubernetes/active-active/preview/create-reaadb.md
> -      name: example-aadb-1
let's stay consistent with the same name as in other examples in the doc.
and keep "example-aadb-1"

2023-03-30 15:05 UTC, alon-zada requested changes
please view one small comment.

2023-03-30 15:30 UTC, kaitlynmichael commented on content/kubernetes/active-active/preview/create-reaadb.md
> +      name: example-reaadb-1
```suggestion
      name: example-aadb-1
```

2023-03-30 15:59 UTC, alon-zada approved these changes

2023-03-30 17:49 UTC, merged