DOC-2062 Global config article for K8s AA public preview
RedisLabs/redislabs-docs pull request #2490
Opened 2023-04-12 20:19 UTC by kaitlynmichael

Jira: DOC-2062
Source material: https://github.com/RedisLabs/redis-enterprise-operator/blob/master/deploy/active_active_database_readme.md#set-the-database-global-configurations-specifications
Staged preview: https://docs.redis.com/staging/DOC-2062/kubernetes/active-active/preview/global-config/

2023-04-12 20:31 UTC, cmilesb commented on content/kubernetes/active-active/preview/global-config.md
> +The Redis Enterprise Active-Active database (REAADB) custom resource contains the field '.spec.globalConfigurations'. This field sets configurations for the Active-Active database across all particip
```suggestion
The Redis Enterprise Active-Active database (REAADB) custom resource contains the field `.spec.globalConfigurations`. This field sets configurations for the Active-Active database across all participating clusters, such as memory size or shard count.
```

Not sure if this is supposed to be back-ticked or not.

2023-04-12 20:31 UTC, cmilesb commented on content/kubernetes/active-active/preview/global-config.md
> +### On an existing participating cluster, do the following
I think instead of having headings - you might want to change these to sentences? The headings seem a little long

2023-04-27 15:43 UTC, alon-zada requested changes
Great!
please view comments.

2023-04-27 15:43 UTC, alon-zada commented on content/kubernetes/active-active/preview/global-config.md
> +  kubectl get reaadb example-aadb-1
also here add that we are getting the REDB named `example-aadb-1` or in the doc state that we are going to work on the REDB named `example-aadb-1` for example

2023-04-27 15:43 UTC, alon-zada commented on content/kubernetes/active-active/preview/global-config.md
> +    kubectl patch reaadb example-aadb-1 --type merge --patch /
also here we should state that the REDB example is named `example-aadb-1`.

2023-04-27 15:43 UTC, alon-zada commented on content/kubernetes/active-active/preview/global-config.md
> +1. Sync the secret.
I think the numbering is broken in this doc.

2023-05-16 14:31 UTC, cmilesb approved these changes
Looks good to me!

2023-05-17 17:42 UTC, kaitlynmichael commented on content/kubernetes/active-active/preview/global-config.md
> +  kubectl patch reaadb example-aadb-1 --type merge --patch /
```suggestion
  kubectl patch reaadb example-aadb-1 --type merge --patch \
```

2023-05-17 17:42 UTC, kaitlynmichael commented on content/kubernetes/active-active/preview/global-config.md
> +    kubectl patch reaadb <reaadb-name> --type merge --patch /
```suggestion
    kubectl patch reaadb <reaadb-name> --type merge --patch \
```

2023-05-17 17:43 UTC, merged