DOC-1844 K8s: Edit RERC
RedisLabs/redislabs-docs pull request #2501
Opened 2023-04-19 19:28 UTC by kaitlynmichael

Jira: DOC-1844
Readme source material: https://github.com/RedisLabs/redis-enterprise-k8s-docs/blob/master/active_active_database_readme.md#update-existing-participating-cluster-rerc-details
Staged preview: https://docs.redis.com/staging/DOC-1844/kubernetes/active-active/preview/edit-rerc/

2023-04-19 19:28 UTC, kaitlynmichael commented
Not ready for review: waiting to meet with SME to get clarification/feedback

2023-05-05 16:59 UTC, rrelledge requested changes

2023-05-05 16:59 UTC, rrelledge commented on content/kubernetes/active-active/preview/edit-rerc.md
> +1. Verify the status each REAADB using that RERC is "Active" and the spec status is "Valid."
Missing word?
```suggestion
1. Verify the status of each REAADB using that RERC is "Active" and the spec status is "Valid."
```

2023-05-05 16:59 UTC, rrelledge commented on content/kubernetes/active-active/preview/edit-rerc.md
> +## Update RERC secret
The numbered steps in this section are not being rendered correctly. Adding tabs/spaces before the non-numbered sentences and code snippets should fix this issue.

2023-05-08 11:26 UTC, alon-zada approved these changes
Great!

2023-05-09 20:12 UTC, merged