Update api.md to include username for Redis Cluster
RedisLabs/redislabs-docs pull request #2527
Opened 2023-04-28 08:40 UTC by guitarrapc

## tl;dr;

api.md missing `username` info in ACL authentication, which is mandatory for Redis Cluster.

I've confirm I can add Redis Cluster (ElastiCache ACL & MemoryDB) with following JSON.

```json
{ "name": "Cache","connectionType": "CLUSTER","seedNodes": [{ "host": "clustercfg.CLUSTER_NAME.xxxxxx.apne1.cache.amazonaws.com","port": 6379 }], "username": "USERNAME", "password": "PASSWORD","tls": { "useTls": true, "clientAuth": false } }
```

2023-04-28 09:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RedisLabs/redislabs-docs?pullRequest=2527) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RedisLabs/redislabs-docs?pullRequest=2527) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RedisLabs/redislabs-docs?pullRequest=2527) it.</sub>

2023-05-05 20:55 UTC, rrelledge requested changes

2023-05-05 20:55 UTC, rrelledge commented on content/ri/using-redisinsight/api.md
>  | password   | string | (optional) The password for your Redis datanase.                                  |
```suggestion
| username   | string | (optional) The username for your Redis database.                                  |
| password   | string | (optional) The password for your Redis database.                                  |
```

2023-05-05 21:05 UTC, rrelledge commented
@ViktarStarastsenka This PR adds `username` to the Redis cluster database parameters table. Should we also add `username` to the example request here?

2023-05-09 16:14 UTC, ViktarStarastsenka commented
@rrelledge , yes please

2023-05-09 17:38 UTC, rrelledge approved these changes

2023-05-10 20:17 UTC, merged