DOC-1934: RC Maintenance Windows
RedisLabs/redislabs-docs pull request #2579
Opened 2023-05-26 14:56 UTC by cmilesb

Staging links: 
https://docs.redis.com/staging/DOC-1934/rc/subscriptions/maintenance/
https://docs.redis.com/staging/DOC-1934/rc/subscriptions/maintenance/set-maintenance-windows/

2023-05-26 23:11 UTC, rrelledge requested changes
Looks good to me aside from some formatting issues and a broken image.

2023-05-26 23:11 UTC, rrelledge commented on content/rc/subscriptions/maintenance/_index.md
> +    - Upgrading to any version with breaking changes
```suggestion
High-impact maintenance can include, but is not limited to:

- Upgrading Redis or an advanced capability to the next major version
- Upgrading to any version with breaking changes
```

2023-05-26 23:11 UTC, rrelledge commented on content/rc/subscriptions/maintenance/_index.md
> +    - Cluster optimization
```suggestion
Low-impact maintenance can include, but is not limited to:

- Upgrading Redis or an advanced capability to the next minor version
- Cluster optimization
```

2023-05-26 23:11 UTC, rrelledge commented on content/rc/subscriptions/maintenance/_index.md
> +High-impact maintenance refers to any activity that may introduce breaking changes. Redis will notify you about any high-impact changes a few weeks before they are released. You can choose to opt-in
"Opt in" as a verb
```suggestion
High-impact maintenance refers to any activity that may introduce breaking changes. Redis will notify you about any high-impact changes a few weeks before they are released. You can opt in to any high-impact changes. If you opt in to high-impact maintenance, Redis will perform it during a maintenance window, or during low-traffic hours if maintenance windows are set to **Automatic**. You will also be notified by email when maintenance starts and ends.
```

2023-05-26 23:11 UTC, rrelledge commented on content/rc/subscriptions/maintenance/set-maintenance-windows.md
> +    {{<image filename="images/rc/subscriptions-set-maintenance-windows.png" alt="The set maintenance windows panel" >}}{{< /image >}}
Broken image

2023-05-29 08:12 UTC, NoamSternRedis commented on content/rc/subscriptions/maintenance/set-maintenance-windows.md
> +You typically do not need to set a maintenance window manually as Redis will attempt to perform maintenance during low-traffic hours when possible. If you want to control when Redis performs maintena
IMO, we don't need to distinguish between the Flexible and Annual subscriptions as both of them are Flexible.

2023-06-01 06:42 UTC, NoamSternRedis commented on content/rc/subscriptions/maintenance/_index.md
> +Urgent maintenance refers to any activity that could affect service and cannot wait for scheduling. Redis can perform urgent maintenance at any time, even if you have set a manual maintenance window
Maybe worth saying something about the fact that it can be a security matter.

2023-06-01 15:02 UTC, cmilesb commented on content/rc/subscriptions/create-flexible-subscription.md
> +| **Maintenance windows** | Determines when Redis can perform [maintenance]({{<relref "/rc/subscriptions/maintenance">}}) on your databases. Select **Manual** if you want set [manual maintenance wind
```suggestion
| **Maintenance windows** | Determines when Redis can perform [maintenance]({{<relref "/rc/subscriptions/maintenance">}}) on your databases. Select **Manual** if you want to set [manual maintenance windows]({{<relref "/rc/subscriptions/maintenance">}}).  |
```

2023-06-11 06:52 UTC, NoamSternRedis approved these changes

2023-06-12 16:24 UTC, merged