K8s: add real words to example values
RedisLabs/redislabs-docs pull request #2606
Opened 2023-06-09 16:31 UTC by kaitlynmichael

DOC-2139
Preview:
- https://docs.redis.com/staging/DOC-2139/kubernetes/active-active/create-aa-crdb-cli/
- https://docs.redis.com/staging/DOC-2139/kubernetes/active-active/prepare-clusters/
- https://docs.redis.com/staging/DOC-2139/kubernetes/active-active/edit-clusters/
- https://docs.redis.com/staging/DOC-2139/kubernetes/active-active/global-config/
- https://docs.redis.com/staging/DOC-2139/kubernetes/active-active/edit-rerc/

2023-06-09 18:21 UTC, kaitlynmichael commented on content/kubernetes/active-active/create-reaadb.md
> +    Example RERC (`rerc2raegan`) for the REC named `rec-arlington` in the namespace `ns-virginia`:
```suggestion
    Example RERC (`rerc-raegan`) for the REC named `rec-arlington` in the namespace `ns-virginia`:
```

2023-06-12 22:07 UTC, kurtfm commented
I think it it all generally looks good to me, but the only thing that caught my eye was that we went from using naming conventions of places and airports to `rerc3` at one point... and then in the edit phase we go back to using the flight motif.  The rerc3 is not wrong... but I guess I would stick with the flight motif.

2023-06-13 16:52 UTC, kaitlynmichael commented
> I think it it all generally looks good to me, but the only thing that caught my eye was that we went from using naming conventions of places and airports to `rerc3` at one point... and then in the edit phase we go back to using the flight motif. The rerc3 is not wrong... but I guess I would stick with the flight motif.

Thanks for catching that @kurtfm ! I repalced the rerc1 and rerc2 but forgot that the edit clusters also uses a third cluster. It's fixed now.

2023-06-13 18:26 UTC, rrelledge requested changes
Looks good to me aside from some typos and formatting issues.

2023-06-13 18:26 UTC, rrelledge commented on content/kubernetes/active-active/edit-clusters.md
> +    This example shoes an admin credentials secret for an REC named `rec-boston`:
```suggestion
    This example shows an admin credentials secret for an REC named `rec-boston`:
```

2023-06-13 18:26 UTC, rrelledge commented on content/kubernetes/active-active/edit-clusters.md
> +  This example shows a RERC custom resource for an REC named `rec-boston` in the namespace `ns-massachusetts`.
```suggestion
  This example shows an RERC custom resource for an REC named `rec-boston` in the namespace `ns-massachusetts`. 
```

2023-06-13 18:26 UTC, rrelledge commented on content/kubernetes/active-active/edit-clusters.md
>  1. Create the RERC custom resource.
The numbered steps aren't rendering correctly in the "Create RERC" section. Adding whitespace before any code samples or extra sentences that belong to a step should fix this.

2023-06-13 18:26 UTC, rrelledge commented on content/kubernetes/active-active/edit-clusters.md
>  ### Edit REAADB spec
There's a similar issue with the numbered steps in "Edit REAADB spec".

2023-06-13 18:26 UTC, rrelledge commented on content/kubernetes/active-active/global-config.md
>  1. Edit or patch the REAADB custom resource with your global configuration changes.
There are some formatting issues on this page. Most of the numbered steps aren't rendering correctly, and there are some formatting issues around the code block starting after "On each other participating cluster, check the secret status."

2023-06-13 18:26 UTC, rrelledge commented on content/kubernetes/active-active/prepare-clusters.md
>  The combination of the REC name and namespace (`<rec-name>.<namespace-name>`) must be unique for each participating cluster the Active-Active database.
Missing word?
```suggestion
The combination of the REC name and namespace (`<rec-name>.<namespace-name>`) must be unique for each participating cluster in the Active-Active database.
```

2023-06-13 18:26 UTC, rrelledge commented on content/kubernetes/active-active/prepare-clusters.md
> +For example, if you have two K8s clusters, each with their own REC named `rec-chicago` in a namespace named `ns-illinois`. The value of `<rec-name>.<namespace-name>` for both RECs would be `rec-chica
Sentence fragment fix
```suggestion
For example, if you have two K8s clusters, each with their own REC named `rec-chicago` in a namespace named `ns-illinois`, the value of `<rec-name>.<namespace-name>` for both RECs would be `rec-chicago.ns-illinois`. These can't be used for the same Active-Active database.
```

2023-06-13 18:26 UTC, rrelledge commented on content/kubernetes/active-active/prepare-clusters.md
>  The admission controller using a validating webhook to dynamically validate resources configured by the operator. The `ValidatingWebhookConfiguration` is required for Active-Active databases. Learn h
```suggestion
The admission controller uses a webhook to dynamically validate resources configured by the operator. The `ValidatingWebhookConfiguration` is required for Active-Active databases. Learn how to enable and configure the admission controller in the [Enable admission controller]({{<relref "/kubernetes/deployment/quick-start.md#enable-the-admission-controller/">}}) section of the [Deploy Redis Enterprise Software for Kubernetes]({{<relref "/kubernetes/deployment/quick-start.md">}}) instructions.
```

2023-06-13 21:37 UTC, cmilesb approved these changes

2023-06-16 17:45 UTC, merged