RDSC-1319: document redis enterprise as target for write behind
RedisLabs/redislabs-docs pull request #2617
Opened 2023-06-14 21:34 UTC by redima

2023-06-15 13:57 UTC, elena-kolevska commented on content/rdi/data-transformation/examples/write-behind-to-redis-example.md
> +The `redis.write` block can be used in the `output` section of the write-behind job in order to enable writing data to Redis target database. Multiple blocks can be used at the same time to write dat
```suggestion
The `redis.write` block can be used in the `output` section of the write-behind job in order to enable writing data to the Redis target database. Multiple blocks can be used at the same time to write data to different data types. The following example captures data modified in the `address:*` keyspace, then creates a new JSON-like string field named `json_addr` and, finally, writes the results to multiple keys in target Redis:
```

2023-06-15 15:07 UTC, yaronp68 requested changes

2023-06-15 15:07 UTC, yaronp68 commented on content/rdi/data-transformation/examples/write-behind-to-redis-example.md
> +# Write-behind to Redis target example
```suggestion
# Write-behind to Redis Enterprise target example
```

2023-06-15 15:07 UTC, yaronp68 commented on content/rdi/data-transformation/examples/write-behind-to-redis-example.md
> +The `redis.write` block can be used in the `output` section of the write-behind job in order to enable writing data to the Redis target database. Multiple blocks can be used at the same time to write
```suggestion
The `redis.write` block can be used in the `output` section of the write-behind job in order to enable writing data to the Redis Enterprise target database. Multiple blocks can be used at the same time to write data to different data types. The following example captures data modified in the `address:*` keyspace, then creates a new JSON-like string field named `json_addr` and, finally, writes the results to multiple keys in target Redis Enteprise:
```

2023-06-15 15:07 UTC, yaronp68 commented on content/rdi/data-transformation/examples/write-behind-to-redis-example.md
> +Run the following command in the source Redis database to test the job:
```suggestion
Run the following command in the source Redis Enterprise database to test the job:
```

2023-06-15 15:07 UTC, yaronp68 commented on content/rdi/data-transformation/examples/write-behind-to-redis-example.md
> +As a result the following 5 keys will be created in the target Redis database (hash, JSON, set, sorted set and stream):
```suggestion
As a result the following 5 keys will be created in the target Redis Enterprise database (hash, JSON, set, sorted set and stream):
```

2023-06-15 15:07 UTC, yaronp68 commented on content/rdi/quickstart/write-behind-guide.md
> +| Redis*     |
```suggestion
| Redis Enterprise     |
```

2023-06-15 15:07 UTC, yaronp68 commented on content/rdi/quickstart/write-behind-guide.md
> +> Note: RDI only supports Redis Enterprise databases as a Redis target. Other distributions of Redis are not supported.
```suggestion
```

2023-06-15 15:07 UTC, yaronp68 commented on content/rdi/write-behind/_index.md
> +linkTitle: Write-behind
```suggestion
linkTitle: write-behind
```

2023-06-16 09:21 UTC, yaronp68 approved these changes

2023-06-16 09:52 UTC, merged