redis-cli TLS connections
RedisLabs/redislabs-docs pull request #2635
Opened 2023-06-20 22:11 UTC by rrelledge

[Staged preview](https://docs.redis.com/staging/DOC-1760/rs/references/cli-utilities/redis-cli/#connect-over-tls)

2023-06-21 05:54 UTC, yoavredis requested changes
Looks OK to me.
But I think it should also be reviewed and approved by those who maintain redis-cli.
I suggest to ask @oranagra to take a look

2023-06-21 13:54 UTC, oranagra reviewed
i've never connected with redis-cli to RE using TLS, so i can't comment on most of that text.
i suggest asking a proxy developer or QA person that tested it.

2023-06-21 13:54 UTC, oranagra commented on content/rs/references/cli-utilities/redis-cli/_index.md
> +redis-cli -h <endpoint> -p <port> slowlog get <number of entries> with-complexity
i suggest dropping the `with-complexity` part,
it's not an official feature

2023-06-26 19:33 UTC, kaitlynmichael approved these changes
One wording suggestion

2023-07-10 19:40 UTC, merged