K8s: added replication status
RedisLabs/redislabs-docs pull request #2666
Opened 2023-07-07 21:12 UTC by kaitlynmichael

preview: https://docs.redis.com/DOC-2449/kubernetes/active-active/edit-rerc/
https://docs.redis.com/DOC-2449/kubernetes/active-active/create-reaadb/

DOC Jira: DOC-2449
Review Jira: DOC-2497

2023-07-09 13:16 UTC, almoggue approved these changes

2023-07-13 05:51 UTC, alon-zada requested changes
Great!
please view one small comment with changes.

2023-07-13 05:51 UTC, alon-zada commented on content/kubernetes/active-active/edit-rerc.md
> +    example-reaadb-2  active   Valid                        up
if you only doing kubectl get reaadb and the reaadb-boeing, in the output it should only exist and not all the REAADBs list that exists in the namespace in the cluster you are at.

2023-07-18 18:54 UTC, kaitlynmichael commented on content/kubernetes/active-active/edit-rerc.md
> +    example-reaadb-2  active   Valid                        up
```suggestion
```

2023-07-18 18:54 UTC, merged