RDSC-1396 `from_entries`, `to_entries` and `filter_entries` custom JMESPath functions
RedisLabs/redislabs-docs pull request #2689
Opened 2023-07-20 14:38 UTC by spicy-sauce

2023-07-21 09:14 UTC, yaronp68 requested changes

2023-07-21 09:14 UTC, yaronp68 commented on content/rdi/reference/jmespath-custom-functions.md
> +| `filter_entries`     | Filters entries in a dictionary (object) based on the given JMESPath predicate                                                      | Input: `{ "name": "John", "age": 30, "co
on -> using

2023-07-25 16:34 UTC, spicy-sauce commented on content/rdi/reference/jmespath-custom-functions.md
> +| `filter_entries`     | Filters entries in a dictionary (object) based on the given JMESPath predicate                                                      | Input: `{ "name": "John", "age": 30, "co
done

2023-07-25 16:44 UTC, yaronp68 approved these changes

2023-08-04 12:59 UTC, merged