K8s 6.4.2-8 release notes
RedisLabs/redislabs-docs pull request #2697
Opened 2023-07-24 18:36 UTC by kaitlynmichael

Preview: https://docs.redis.com/staging/DOC-2519/kubernetes/release-notes/6-4-2-releases/6-4-2-8/

2023-07-26 19:13 UTC, bascar requested changes
Known limitations, line 160, we can drop {{<expand "5.4.10 negatively impacts 5.4.6 (RED-37233)">}} Kubernetes-based 5.4.10 deployments seem to negatively impact existing 5.4.6 deployments that share a Kubernetes cluster. {{</expand>}}

2023-07-27 14:17 UTC, yuvallevy2 commented on content/kubernetes/release-notes/6-4-2-releases/6-4-2-6.md
> -* **Operator**: `registry.connect.redhat.com/redislabs/redis-enterprise-operator:6.4.2-6`s
is this intentional?

2023-07-27 14:18 UTC, kaitlynmichael commented on content/kubernetes/release-notes/6-4-2-releases/6-4-2-6.md
> -* **Operator**: `registry.connect.redhat.com/redislabs/redis-enterprise-operator:6.4.2-6`s
I think it was a typo, so I removed it.

2023-07-27 14:19 UTC, yuvallevy2 approved these changes

2023-07-27 14:23 UTC, merged