DOC-2530: Add skip for a week to maintenance window docs
RedisLabs/redislabs-docs pull request #2801
Opened 2023-08-28 20:41 UTC by cmilesb

Staging link: https://docs.redis.com/staging/DOC-2530/rc/subscriptions/maintenance/set-maintenance-windows

Releasing 9/7.

2023-08-29 07:10 UTC, NoamSternRedis requested changes

2023-08-29 14:59 UTC, NoamSternRedis requested changes

2023-08-29 14:59 UTC, NoamSternRedis commented on content/rc/subscriptions/maintenance/set-maintenance-windows.md
> +Redis will still perform [urgent maintenance]({{<relref "/rc/subscriptions/maintenance#urgent-maintenance">}}) on your subscription during the skipped maintenance period.
Let's be more gentle here. "Redis will.. " is not correct. 
We might do it, only if we have to

2023-08-29 15:00 UTC, NoamSternRedis commented
@cmilesb, we should postpone the release date by a week or two. Still don't have the exact time. But let's postpone for now to September 14.

2023-09-01 18:25 UTC, rrelledge approved these changes
Looks good to me.

2023-11-29 15:28 UTC, merged