RDSC-1499: support for redis lookup transformation block
RedisLabs/redislabs-docs pull request #2842
Opened 2023-09-14 13:36 UTC by vd2org

2023-09-14 13:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RedisLabs/redislabs-docs?pullRequest=2842) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RedisLabs/redislabs-docs?pullRequest=2842) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RedisLabs/redislabs-docs?pullRequest=2842) it.</sub>

2023-09-14 14:24 UTC, spicy-sauce commented
@vd2org you should rebase it as it was forked from the `master` and should be merged to `rdi-preview-build`

2023-09-14 14:52 UTC, spicy-sauce approved these changes

2023-09-15 15:21 UTC, redima commented
so do we expect a data engineer to be a redis expert now? I remember this was a problem and the similar syntax proposal got rejected when we worked on `redis.write` block.

2023-09-15 15:39 UTC, redima commented
Also, I think it should be limited to a set of specific read commands, as currently I can delete of modify data by passing `DEL` as a command.

2023-09-18 05:32 UTC, spicy-sauce approved these changes

2023-09-18 06:44 UTC, spicy-sauce commented
> so do we expect a data engineer to be a redis expert now? I remember this was a problem and the similar syntax proposal got rejected when we worked on `redis.write` block.

We can just wrap it with the supported commands, for example, `hash` instead of `hgetall` and `hget` with the field and key.
Not sure if this should be handled at this point, but probably such an abstraction is preferred. 
@yaronp68 WDYT?

2023-09-18 06:45 UTC, spicy-sauce commented
> Also, I think it should be limited to a set of specific read commands, as currently I can delete of modify data by passing `DEL` as a command.

I agree, see my answer above, if we support only `hash`, `json` and other read commands, this won't be available.

2023-09-18 08:18 UTC, yaronp68 commented
> > so do we expect a data engineer to be a redis expert now? I remember this was a problem and the similar syntax proposal got rejected when we worked on `redis.write` block.
> 
> We can just wrap it with the supported commands, for example, `hash` instead of `hgetall` and `hget` with the field and key. Not sure if this should be handled at this point, but probably such an abstraction is preferred. @yaronp68 WDYT?

I think we can just specify the expected key type: Hash, JSON, Set etc and not the command. Obviously only a handful of read commands (and some members commands)

2023-09-18 08:33 UTC, yaronp68 commented
Full list of commands Lookup should support and the value user should specify:
HGETALL - Hash
JSON.GET - JSON
SMEMBERS - Set.All
ZRANGE - SortedSet.Range AND ZRANGE with BYSCORE - SortedSet.Score
ZPOPMAX - SortedSet.Max
ZPOPMIN - SortedSet.Min
GET - String
MGET - Strings
(we can add a substring command later)

2023-09-18 08:59 UTC, spicy-sauce commented
> Full list of commands Lookup should support and the value user should specify: HGETALL - Hash JSON.GET - JSON SMEMBERS - Set.All ZRANGE - SortedSet.Range AND ZRANGE with BYSCORE - SortedSet.Score ZPOPMAX - SortedSet.Max ZPOPMIN - SortedSet.Min GET - String MGET - Strings (we can add a substring command later)

Let's have a new issue for this, as it was already implemented like this (this is the adjustments in the documentation).

2023-09-18 13:18 UTC, yaronp68 requested changes

2023-09-18 13:18 UTC, yaronp68 commented on content/rdi/reference/data-transformation-block-types/lookup.md
> +| [**cmd**](#option1fields)        | `string`       | Command to execute<br/>   | yes      |
```suggestion
| [**cmd**](#option1fields)        | `string`       | Redis command to execute<br/>   | yes      |
```

2023-09-18 13:18 UTC, yaronp68 commented on content/rdi/reference/data-transformation-block-types/lookup.md
> +
Add list of allowed commands (even if we are not validating these can only be commands that do read of one or more keys / members
Also we should document how different commands response will look like in a field

2023-09-19 16:41 UTC, yaronp68 approved these changes

2023-09-19 16:44 UTC, merged