Added a script to install the dependencies
RedisLabs/redislabs-docs pull request #952
Opened 2020-07-24 06:31 UTC by viragtripathi

Added a simple script to install the dependencies to avoid the manual steps which can lead to errors.

2020-07-24 06:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RedisLabs/redislabs-docs?pullRequest=952) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RedisLabs/redislabs-docs?pullRequest=952) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RedisLabs/redislabs-docs?pullRequest=952) it.</sub>

2020-11-02 09:30 UTC, bmansheim commented
@K-Jo We can close this because in 6.0.12 there is no need to install dependencies, correct?

2020-11-24 09:50 UTC, bmansheim commented
@K-Jo Looks like there will be dependencies until 6.0.16. Should we merge this until then or just wait?

2020-11-24 10:31 UTC, K-Jo requested changes

2020-11-24 10:31 UTC, K-Jo commented on content/modules/redisgears/installing-redisgears.md
> +cat install_rg_dependencies.sh
This should be a code snippet

2020-12-23 09:57 UTC, bmansheim commented
This behavior will change in 6.0.12.

2020-12-23 09:57 UTC, closed without merging